routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
// Auth::routes();

// Route::get('/register/{lang?}', 'Auth\RegisterController@showRegistrationForm')->name('register');
// Route::get('/login/{lang?}', 'Auth\LoginController@showLoginForm')->name('login');
// Route::get('/reset/password/{lang?}', 'Auth\LoginController@showLinkRequestForm')->name('password.request');

require __DIR__.'/auth.php';

Route::get('/', ['uses' => 'HomeController@landingPage'])->middleware(['auth','XSS']);
Route::get('/home', ['as' => 'home','uses' => 'HomeController@index'])->middleware(['auth','XSS']);
Route::get('/check','HomeController@check')->middleware(['auth','XSS']);
Route::get('/checks','HomeController@homeCheck')->middleware(['auth','XSS']);
Route::get('dashboard-view',['as' => 'dashboard.view','uses' => 'HomeController@filterView'])->middleware(['auth', 'XSS']);

// User Module
Route::get('users/{view?}',['as' => 'users','uses' => 'UserController@index'])->middleware(['auth', 'XSS']);
Route::get('users-view',['as' => 'filter.user.view','uses' => 'UserController@filterUserView'])->middleware(['auth', 'XSS']);
Route::get('checkuserexists',['as' => 'user.exists','uses' => 'UserController@checkUserExists'])->middleware(['auth', 'XSS']);
Route::get('profile',['as' => 'profile','uses' =>'UserController@profile'])->middleware(['auth','XSS']);
Route::post('/profile',['as' => 'update.profile','uses' =>'UserController@updateProfile'])->middleware(['auth','XSS']);
Route::get('user/info/{id}',['as' => 'users.info','uses' =>'UserController@userInfo'])->middleware(['auth','XSS']);
Route::get('user/{id}/info/{type}',['as' => 'user.info.popup','uses' =>'UserController@getProjectTask'])->middleware(['auth','XSS']);
Route::delete('users/{id}', ['as' => 'user.destroy', 'uses' => 'UserController@destroy'])->middleware(['auth', 'XSS']);
// End User Module

// Language Module
Route::GET('/lang/create',['as' => 'lang.create','uses' =>'UserController@createLang'])->middleware(['auth','XSS']);
Route::GET('/lang/{lang}',['as' => 'lang','uses' =>'UserController@lang'])->middleware(['auth','XSS']);
Route::POST('/lang',['as' => 'lang.store','uses' =>'UserController@storeLang'])->middleware(['auth','XSS']);
Route::POST('/lang/data/{lang}',['as' => 'lang.store.data','uses' =>'UserController@storeLangData'])->middleware(['auth','XSS']);
Route::get('/lang/change/{lang}',['as' => 'lang.change','uses' =>'UserController@changeLang'])->middleware(['auth','XSS']);
Route::delete('/lang/{id}',['as' => 'lang.destroy','uses' =>'UserController@destroyLang'])->middleware(['auth','XSS']);
// End Language Module

// Search
Route::get('/search',['as' => 'search.json','uses' =>'UserController@search'])->middleware(['auth','XSS']);
// end

// Milestone Module
Route::get('projects/{id}/milestone', ['as' => 'project.milestone','uses' => 'ProjectController@milestone'])->middleware(['auth', 'XSS']);
Route::post('projects/{id}/milestone', ['as' => 'project.milestone.store', 'uses' => 'ProjectController@milestoneStore'])->middleware(['auth', 'XSS']);
Route::get('projects/milestone/{id}/edit', ['as' => 'project.milestone.edit', 'uses' => 'ProjectController@milestoneEdit'])->middleware(['auth', 'XSS']);
Route::post('projects/milestone/{id}', ['as' => 'project.milestone.update', 'uses' => 'ProjectController@milestoneUpdate'])->middleware(['auth', 'XSS']);
Route::delete('projects/milestone/{id}', ['as' => 'project.milestone.destroy', 'uses' => 'ProjectController@milestoneDestroy'])->middleware(['auth', 'XSS']);
Route::get('projects/milestone/{id}/show', ['as' => 'project.milestone.show', 'uses' => 'ProjectController@milestoneShow'])->middleware(['auth', 'XSS']);
// End Milestone

// Project Module
Route::get('invite-project-member/{id}',['as' => 'invite.project.member.view','uses' => 'ProjectController@inviteMemberView'])->middleware(['auth', 'XSS']);
Route::post('invite-project-user-member',['as' => 'invite.project.user.member','uses' => 'ProjectController@inviteProjectUserMember'])->middleware(['auth', 'XSS']);
Route::get('project/{view?}',['as' => 'projects.list','uses' => 'ProjectController@index'])->middleware(['auth', 'XSS']);
Route::get('projects-view',['as' => 'filter.project.view','uses' => 'ProjectController@filterProjectView'])->middleware(['auth', 'XSS']);
Route::post('projects/{id}/store-stages/{slug}', 'ProjectController@storeProjectTaskStages')->name('project.stages.store')->middleware(['auth', 'XSS']);
Route::patch('remove-user-from-project/{project_id}/{user_id}', ['as' => 'remove.user.from.project','uses' => 'ProjectController@removeUserFromProject'])->middleware(['auth', 'XSS']);
Route::get('projects-users',['as' => 'project.user','uses' => 'ProjectController@loadUser'])->middleware(['auth', 'XSS']);
Route::get('projects/{id}/gantt/{duration?}',['as' => 'projects.gantt','uses' =>'ProjectController@gantt'])->middleware(['auth','XSS']);
Route::post('projects/{id}/gantt',['as' => 'projects.gantt.post','uses' =>'ProjectController@ganttPost'])->middleware(['auth','XSS']);
Route::resource('projects', 'ProjectController')->middleware(['auth', 'XSS']);


// User Permission
Route::get('projects/{id}/user/{uid}/permission',['as' => 'projects.user.permission','uses' =>'ProjectController@userPermission'])->middleware(['auth','XSS']);
Route::post('projects/{id}/user/{uid}/permission',['as' => 'projects.user.permission.store','uses' =>'ProjectController@userPermissionStore'])->middleware(['auth','XSS']);
// End Project Module

// user module
Route::get('add-user',['as' => 'add.user.view','uses' => 'UserController@addUser'])->middleware(['auth', 'XSS']);
Route::get('check-user-exist',['as' => 'add.user.exists','uses' => 'UserController@addUserExists'])->middleware(['auth', 'XSS']);
Route::post('add-user-member',['as' => 'add.user.member','uses' => 'UserController@addUserMember'])->middleware(['auth', 'XSS']);
Route::any('user-reset-password/{id}', 'UserController@userPassword')->name('user.reset');
Route::post('user-reset-password/{id}', 'UserController@userPasswordReset')->name('user.password.update');

// Task Module
Route::get('stage/{id}/tasks', ['as' => 'stage.tasks','uses' => 'ProjectTaskController@getStageTasks'])->middleware(['auth', 'XSS']);

// Project Task Module
Route::get('/projects/{id}/task',['as' => 'projects.tasks.index','uses' =>'ProjectTaskController@index'])->middleware(['auth','XSS']);
Route::get('/projects/{pid}/task/{sid}',['as' => 'projects.tasks.create','uses' =>'ProjectTaskController@create'])->middleware(['auth','XSS']);
Route::post('/projects/{pid}/task/{sid}',['as' => 'projects.tasks.store','uses' =>'ProjectTaskController@store'])->middleware(['auth','XSS']);
Route::get('/projects/{id}/task/{tid}/show',['as' => 'projects.tasks.show','uses' =>'ProjectTaskController@show'])->middleware(['auth','XSS']);
Route::get('/projects/{id}/task/{tid}/edit',['as' => 'projects.tasks.edit','uses' =>'ProjectTaskController@edit'])->middleware(['auth','XSS']);
Route::post('/projects/{id}/task/update/{tid}',['as' => 'projects.tasks.update','uses' =>'ProjectTaskController@update'])->middleware(['auth','XSS']);
Route::delete('/projects/{id}/task/{tid}',['as' => 'projects.tasks.destroy','uses' =>'ProjectTaskController@destroy'])->middleware(['auth','XSS']);
Route::patch('/projects/{id}/task/order',['as' => 'tasks.update.order','uses' =>'ProjectTaskController@taskOrderUpdate'])->middleware(['auth','XSS']);
Route::patch('update-task-priority-color', ['as' => 'update.task.priority.color','uses' => 'ProjectTaskController@updateTaskPriorityColor'])->middleware(['auth', 'XSS']);

Route::post('/projects/{id}/comment/{tid}/file',['as' => 'comment.store.file','uses' =>'ProjectTaskController@commentStoreFile']);
Route::delete('/projects/{id}/comment/{tid}/file/{fid}',['as' => 'comment.destroy.file','uses' =>'ProjectTaskController@commentDestroyFile']);
Route::post('/projects/{id}/comment/{tid}',['as' => 'comment.store','uses' =>'ProjectTaskController@commentStore']);
Route::delete('/projects/{id}/comment/{tid}/{cid}',['as' => 'comment.destroy','uses' =>'ProjectTaskController@commentDestroy']);
Route::post('/projects/{id}/checklist/{tid}',['as' => 'checklist.store','uses' =>'ProjectTaskController@checklistStore']);
Route::post('/projects/{id}/checklist/update/{cid}',['as' => 'checklist.update','uses' =>'ProjectTaskController@checklistUpdate']);
Route::delete('/projects/{id}/checklist/{cid}',['as' => 'checklist.destroy','uses' =>'ProjectTaskController@checklistDestroy']);
Route::post('/projects/{id}/change/{tid}/fav',['as' => 'change.fav','uses' =>'ProjectTaskController@changeFav']);
Route::post('/projects/{id}/change/{tid}/complete',['as' => 'change.complete','uses' =>'ProjectTaskController@changeCom']);
Route::post('/projects/{id}/change/{tid}/progress',['as' => 'change.progress','uses' =>'ProjectTaskController@changeProg']);
Route::get('/projects/task/{id}/get',['as' => 'projects.tasks.get','uses' =>'ProjectTaskController@taskGet'])->middleware(['auth','XSS']);

Route::get('taskboard/{view?}',['as' => 'taskBoard.view','uses' => 'ProjectTaskController@taskBoard'])->middleware(['auth', 'XSS']);
Route::get('taskboard-view',['as' => 'project.taskboard.view','uses' => 'ProjectTaskController@taskboardView'])->middleware(['auth', 'XSS']);
Route::get('/calendar/{id}/show',['as' => 'task.calendar.show','uses' =>'ProjectTaskController@calendarShow'])->middleware(['auth','XSS']);
Route::post('/calendar/{id}/drag',['as' => 'task.calendar.drag','uses' =>'ProjectTaskController@calendarDrag']);

resources/views/projects/gantt.blade.php
@extends('layouts.admin')

@section('title') {{__('Gantt Chart')}} @endsection

@section('action-button')
    <div class="btn-group mt-1 mr-2" id="change_view" role="group">
        <a href="{{route('projects.gantt',[$project->id,'Quarter Day'])}}" class="btn btn-sm btn-neutral @if($duration == 'Quarter Day')active @endif" data-value="Quarter Day">{{__('Quarter Day')}}</a>
        <a href="{{route('projects.gantt',[$project->id,'Half Day'])}}" class="btn btn-sm btn-neutral @if($duration == 'Half Day')active @endif" data-value="Half Day">{{__('Half Day')}}</a>
        <a href="{{route('projects.gantt',[$project->id,'Day'])}}" class="btn btn-sm btn-neutral @if($duration == 'Day')active @endif" data-value="Day">{{__('Day')}}</a>
        <a href="{{route('projects.gantt',[$project->id,'Week'])}}" class="btn btn-sm btn-neutral @if($duration == 'Week')active @endif" data-value="Week">{{__('Week')}}</a>
        <a href="{{route('projects.gantt',[$project->id,'Month'])}}" class="btn btn-sm btn-neutral @if($duration == 'Month')active @endif" data-value="Month">{{__('Month')}}</a>
    </div>
    <a href="{{route('projects.show',[$project->id])}}" class="btn btn-sm btn-white rounded-circle btn-icon-only ml-2">
        <span class="btn-inner--icon"><i class="fas fa-arrow-left"></i></span>
    </a>
@endsection

@section('content')
    <?php $permissions = Auth::user()->getPermission($project->id); ?>

    <div class="row">
        <div class="col-12">
            <div class="card card-stats border-0">
                @if($project)
                    <div class="gantt-target"></div>
                @else
                    <h1>404</h1>
                    <div class="page-description">
                        {{ __('Page Not Found') }}
                    </div>
                    <div class="page-search">
                        <p class="text-muted mt-3">{{ __("It's looking like you may have taken a wrong turn. Don't worry... it happens to the best of us. Here's a little tip that might help you get back on track.")}}</p>
                        <div class="mt-3">
                            <a class="btn-return-home badge-blue" href="{{route('home')}}"><i class="fas fa-reply"></i> {{ __('Return Home')}}</a>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection
@if($project)
    @push('css')
        <link rel="stylesheet" href="{{asset('assets/css/frappe-gantt.css')}}"/>
    @endpush
    @push('script')
        @php
            $currantLang = basename(App::getLocale());
        @endphp
        <script>
            const month_names = {
                "{{$currantLang}}": [
                    '{{__('January')}}',
                    '{{__('February')}}',
                    '{{__('March')}}',
                    '{{__('April')}}',
                    '{{__('May')}}',
                    '{{__('June')}}',
                    '{{__('July')}}',
                    '{{__('August')}}',
                    '{{__('September')}}',
                    '{{__('October')}}',
                    '{{__('November')}}',
                    '{{__('December')}}'
                ],
                "en": [
                    'January',
                    'February',
                    'March',
                    'April',
                    'May',
                    'June',
                    'July',
                    'August',
                    'September',
                    'October',
                    'November',
                    'December'
                ],
            };
        </script>
        <script src="{{asset('assets/js/frappe-gantt.js')}}"></script>
        <script>
            var tasks = JSON.parse('{!! addslashes(json_encode($tasks)) !!}');
            var gantt_chart = new Gantt(".gantt-target", tasks, {
                custom_popup_html: function (task) {
                    return `<div class="details-container">
                                <div class="title">${task.name} <span class="badge float-right" style="background-color:${task.custom_class};color:white">${task.extra.priority}</span></div>
                                <div class="subtitle">
                                    <b>${task.progress}%</b> {{ __('Progress')}} <br>
                                    <b>${task.extra.comments}</b> {{ __('Comments')}} <br>
                                    <b>{{ __('Duration')}}</b> ${task.extra.duration}
                                </div>
                            </div>
                          `;
                },
                on_click: function (task) {
                    //console.log(task);
                },
                on_date_change: function (task, start, end) {
                    task_id = task.id;
                    start = moment(start);
                    end = moment(end);
                    $.ajax({
                        url: "{{route('projects.gantt.post',[$project->id])}}",
                        data: {
                            start: start.format('YYYY-MM-DD HH:mm:ss'),
                            end: end.format('YYYY-MM-DD HH:mm:ss'),
                            task_id: task_id,
                        },
                        type: 'POST',
                        success: function (data) {

                        },
                        error: function (data) {
                            show_toastr('Error', '{{ __("Some Thing Is Wrong!")}}', 'error');
                        }
                    });
                },
                view_mode: '{{$duration}}',
                language: '{{$currantLang}}'
            });
        </script>
    @endpush
@endif

resources/views/projects/import.blade.php
 @php
$logo = \App\Models\Utility::get_file('uploads/sample/');
@endphp

<div class="card bg-none card-box">
    {{ Form::open(array('route' => array('project.import'),'method'=>'post', 'enctype' => "multipart/form-data")) }}
    <div class="row" style="padding: 15px 15px;">
        <div class="col-md-12 mb-2">
            <div class="d-flex align-items-center justify-content-between">
                {{Form::label('file',__('Download sample customer CSV file'),['class'=>'form-control-label w-auto m-0'])}}
                <div>
                    <a href="{{$logo.'sample-client.xlsx'}}" class="btn btn-sm btn-primary">
                        <i class="fa fa-download"></i> {{__('Download')}}
                    </a>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            {{Form::label('file',__('Select CSV File'),['class'=>'form-control-label'])}}
            <div class="choose-file form-group">
                <label for="file" class="form-control-label">
                    <div>{{__('Choose file here')}}</div>
                    <input type="file" class="form-control" name="file" id="file" data-filename="upload_file" required>
                </label>
                <p class="upload_file"></p>
            </div>
        </div>
        <div class="col-md-12 mt-2 text-right">
            <input type="submit" value="{{__('Upload')}}" class="btn btn-sm btn-primary">
            <input type="button" value="{{__('Cancel')}}" class="btn btn-sm btn-secondary" data-dismiss="modal">
        </div>
    </div>
    {{ Form::close() }}
</div>

resources/views/projects/list.blade.php
@php
$logo_path = \App\Models\Utility::get_file('/');
@endphp
<div class="col-12">
    <div class="card">
        <div class="table-responsive">
            <table class="table align-items-center">
                <thead>
                <tr>
                    <th scope="col" class="sort" data-sort="name">{{__('Project')}}</th>
                    <th scope="col" class="sort" data-sort="completion">{{__('Budget')}}</th>
                    <th scope="col" class="sort" data-sort="completion">{{__('Estimated Hours')}}</th>
                    <th scope="col" class="sort" data-sort="status">{{__('Status')}}</th>
                    <th scope="col">{{__('Users')}}</th>
                    <th scope="col" class="sort" data-sort="completion">{{__('Completion')}}</th>
                    <th scope="col"></th>
                </tr>
                </thead>
                <tbody class="list">
                @if(isset($projects) && !empty($projects) && count($projects) > 0)
                    @foreach ($projects as $key => $project)
                        <tr>
                            <th scope="row">
                                <div class="media align-items-center">
                                    <div>


                                    @if($project->image)

                                    <img src="{{$logo_path.$project->image}}" alt="{{ $project->name }}"  class="avatar rounded-circle" id="blah" />
                                    @else

                                     <img {{ $project->img_image }} class="avatar rounded-circle">
                                    @endif



                                    </div>
                                    <div class="media-body ml-4">
                                        @if($project->is_active == 1)
                                            <a href="{{ route('projects.show',$project) }}" class="name mb-0 h6 text-sm">{{ $project->name }}</a>
                                        @else
                                            <a href="#" class="name mb-0 h6 text-sm">{{ $project->name }}</a>
                                        @endif
                                        <br>
                                        <span class="badge badge-xs badge-{{ (\Auth::user()->checkProject($project->id) == 'Owner') ? 'success' : 'warning'  }}" data-toggle="tooltip" data-placement="bottom" data-original-title="{{__('You are ') .__(ucfirst($project->permission()))}}">{{ __(\Auth::user()->checkProject($project->id)) }}</span>
                                    </div>
                                </div>
                            </th>
                            <td>
                                <div class="media align-items-center">
                                   {{$project->currency}} {{$project->budget}}
                                </div>
                            </td>
                            <td>
                                <div class="media align-items-center">
                                    {{$project->estimated_hrs}}
                                </div>
                            </td>
                            <td>
                                <span class="badge badge-dot mr-4">
                                      <i class="bg-{{\App\Models\Project::$status_color[$project->status]}}"></i>
                                      <span class="status">{{ __(\App\Models\Project::$status[$project->status]) }}</span>
                                </span>
                            </td>

                            <td>
                                <div class="avatar-group" id="project_{{ $project->id }}">
                                    @if(isset($project->users) && !empty($project->users) && count($project->users) > 0)
                                        @foreach($project->users as $key => $user)
                                            @if($key < 3)
                                                <a href="{{route('users.info', $user->id)}}" class="avatar rounded-circle avatar-sm">




                                                       @if($user->avatar)

                                                        <img src="{{$logo_path.$user->avatar}}" alt="{{ $user->name }}" title="{{ $user->name }}" />
                                                        @else

                                                         <img {{ $user->img_avatar }} title="{{ $user->name }}">
                                                        @endif









                                                </a>
                                            @else
                                                @break
                                            @endif
                                        @endforeach
                                        @if(count($project->users) > 3)
                                            <a href="#" class="avatar rounded-circle avatar-sm">
                                                <img avatar="+ {{ count($project->users)-3 }}">
                                            </a>
                                        @endif
                                    @else
                                        {{ __('-') }}
                                    @endif
                                </div>
                            </td>
                            <td>
                                <div class="d-flex align-items-center">
                                    <span class="completion mr-2">{{ $project->project_progress()['percentage'] }}</span>
                                    <div>
                                        <div class="progress" style="width: 100px;">
                                            <div class="progress-bar bg-{{ $project->project_progress()['color'] }}" role="progressbar" aria-valuenow="{{ $project->project_progress()['percentage'] }}" aria-valuemin="0" aria-valuemax="100" style="width: {{ $project->project_progress()['percentage'] }};"></div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td class="text-right w-15">
                                @if($project->is_active == 1)
                                    @if(\Auth::user()->checkProject($project->id) == 'Owner')
                                        <div class="actions">
                                            <a href="#" data-url="{{ route('invite.project.member.view', $project->id) }}" data-ajax-popup="true" data-size="lg" data-title="{{__('Invite Member')}}" class="action-item px-2" data-toggle="tooltip" data-original-title="{{__('Invite Member')}}">
                                                <i class="fas fa-paper-plane"></i>
                                            </a>
                                            <a href="{{ route('projects.edit',$project) }}" class="action-item px-2" data-toggle="tooltip" data-original-title="{{__('Edit')}}">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            <a href="#" class="action-item text-danger px-2" data-toggle="tooltip" data-original-title="{{__('Delete')}}" data-confirm="{{__('Are You Sure?')}}|{{__('This action can not be undone. Do you want to continue?')}}" data-confirm-yes="document.getElementById('delete-project-{{$project->id}}').submit();">
                                                <i class="fas fa-trash-alt"></i>
                                            </a>
                                        </div>
                                        {!! Form::open(['method' => 'DELETE', 'route' => ['projects.destroy',$project->id],'id'=>'delete-project-'.$project->id]) !!}
                                        {!! Form::close() !!}
                                    @endif
                                @else
                                    <div class="actions text-center px-4">
                                        <a href="#" class="action-item" data-toggle="tooltip" data-original-title="{{__('Locked')}}">
                                            <i class="fas fa-lock"></i>
                                        </a>
                                    </div>
                                @endif
                            </td>
                        </tr>
                    @endforeach
                @else
                    <tr>
                        <th scope="col" colspan="7"><h6 class="text-center">{{__('No Projects Found.')}}</h6></th>
                    </tr>
                @endif
                </tbody>
            </table>
        </div>
    </div>
</div>

resources/views/projects/timesheet_list.blade.php
@extends('layouts.admin')

@section('title')
    {{__('Timesheet List')}}
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row">
                        <div class="col-md-6 weekly-dates-div pt-1">
                            <a href="#" class="action-item previous"><i class="fas fa-arrow-left"></i></a>
                            <span class="weekly-dates"></span>
                            <input type="hidden" id="weeknumber" value="0">
                            <input type="hidden" id="selected_dates">
                            <a href="#" class="action-item next"><i class="fas fa-arrow-right"></i></a>
                        </div>
                        <div class="col text-right pt-1">
                            <div class="custom-control custom-checkbox timesheet-owner">
                                <input type="checkbox" class="custom-control-input owner-timesheet-status" checked id="owner-check">
                                <label class="custom-control-label" for="owner-check">{{__('See as Owner')}}</label>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-wrapper project-timesheet overflow-auto"></div>
                <div class="text-center notfound-timesheet">
                    <div class="empty-project-text text-center p-3 min-h-300">
                        <h5 class="pt-5">{{ __("We couldn't find any data") }}</h5>
                        <p class="m-0">{{ __("Sorry we can't find any timesheet records on this week.") }}</p>
                        <p class="m-0">{{ __("To add timesheet record go to ") }}<a href="{{route('projects.index')}}">{{__('projects')}}</a>.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        function ajaxFilterTimesheetTableView() {
            var mainEle = $('.project-timesheet');
            var notfound = $('.notfound-timesheet');
            var week = parseInt($('#weeknumber').val());
            var project_id = '0';
            var isowner = $('.owner-timesheet-status').prop('checked');
            var data = {
                week: week,
                project_id: project_id,
            }
            data.isowner = isowner;

            $.ajax({
                url: '{{ route('filter.timesheet.table.view') }}',
                data: data,
                success: function (data) {
                    $('.weekly-dates-div .weekly-dates').text(data.onewWeekDate);
                    $('.weekly-dates-div #selected_dates').val(data.selectedDate);

                    $.each(data.sectiontasks, function (i, item) {

                        var optionhtml = '';

                        if (item.section_id != 0 && item.section_name != '' && item.tasks.length > 0) {
                            optionhtml += `<a href="#" class="dropdown-item select-sub-heading" data-tasks-count="` + item.tasks.length + `">` + item.section_name + `</a>`;
                        }
                        $.each(item.tasks, function (ji, jitem) {
                            optionhtml += `<a href="#" class="dropdown-item select-task" data-task-id="` + jitem.task_id + `">` + jitem.task_name + `</a>`;
                        });
                    });

                    if (data.totalrecords == 0) {
                        mainEle.hide();
                        notfound.css('display', 'block');
                    } else {
                        notfound.hide();
                        mainEle.show();
                    }
                    mainEle.html(data.html);
                }
            });
        }

        $(function () {
            ajaxFilterTimesheetTableView();
        });

        $(document).on('click', '.weekly-dates-div .action-item', function () {
            var weeknumber = parseInt($('#weeknumber').val());
            if ($(this).hasClass('previous')) {
                weeknumber--;
                $('#weeknumber').val(weeknumber);
            } else if ($(this).hasClass('next')) {
                weeknumber++;
                $('#weeknumber').val(weeknumber);
            }
            ajaxFilterTimesheetTableView();
        });


        $(document).on('change', '#time_hour, #time_minute', function () {

            var hour = $('#time_hour').children("option:selected").val();
            var minute = $('#time_minute').children("option:selected").val();
            var total = $('#totaltasktime').val().split(':');

            if (hour == '00' && minute == '00') {
                $(this).val('');
                return;
            }

            hour = hour != '' ? hour : 0;
            hour = parseInt(hour) + parseInt(total[0]);

            minute = minute != '' ? minute : 0;
            minute = parseInt(minute) + parseInt(total[1]);

            if (minute > 50) {
                minute = minute - 60;
                hour++;
            }

            hour = hour < 10 ? '0' + hour : hour;
            minute = minute < 10 ? '0' + minute : minute;

            $('.display-total-time small').text('{{ __("Total Time worked on this task") }} : ' + hour + ' {{ __("Hours") }} ' + minute + ' {{ __("Minutes") }}');
        });

        {{--@if(isset($permissions) && in_array('show as admin timesheet',$permissions))--}}
        $(document).on('click', '.timesheet-owner .owner-timesheet-status', function (e) {
            ajaxFilterTimesheetTableView();
        });
        {{--@endif--}}
    </script>
@endpush