routes/web.php
Route::post('/invoice-pay-with-flaterwave',['as' => 'invoice.pay.with.flaterwave','uses' =>'FlutterwavePaymentController@invoicePayWithFlutterwave'])->middleware(['auth','XSS']);
Route::get('/invoice/flaterwave/{txref}/{invoice_id}', ['as' => 'invoice.flaterwave','uses' => 'FlutterwavePaymentController@getInvoicePaymentStatus']);

Route::post('/invoice-pay-with-razorpay',['as' => 'invoice.pay.with.razorpay','uses' =>'RazorpayPaymentController@invoicePayWithRazorpay'])->middleware(['auth','XSS']);
Route::get('/invoice/razorpay/{txref}/{invoice_id}', ['as' => 'invoice.razorpay','uses' => 'RazorpayPaymentController@getInvoicePaymentStatus']);

Route::post('/invoice-pay-with-paytm',['as' => 'invoice.pay.with.paytm','uses' =>'PaytmPaymentController@invoicePayWithPaytm'])->middleware(['auth','XSS']);
Route::post('/invoice/paytm/{invoice}', ['as' => 'invoice.paytm','uses' => 'PaytmPaymentController@getInvoicePaymentStatus']);

Route::post('/invoice-pay-with-mercado',['as' => 'invoice.pay.with.mercado','uses' =>'MercadoPaymentController@invoicePayWithMercado'])->middleware(['auth','XSS']);
Route::any('/invoice/mercado/{invoice}', ['as' => 'invoice.mercado.callback','uses' => 'MercadoPaymentController@getInvoicePaymentStatus']);

Route::post('/invoice-pay-with-mollie',['as' => 'invoice.pay.with.mollie','uses' =>'MolliePaymentController@invoicePayWithMollie'])->middleware(['XSS']);
Route::get('/invoice/mollie/{invoice}', ['as' => 'invoice.mollie','uses' => 'MolliePaymentController@getInvoicePaymentStatus']);

Route::post('/invoice-pay-with-skrill',['as' => 'invoice.pay.with.skrill','uses' =>'SkrillPaymentController@invoicePayWithSkrill'])->middleware(['XSS']);
Route::get('/invoice/skrill/{invoice}', ['as' => 'invoice.skrill','uses' => 'SkrillPaymentController@getInvoicePaymentStatus']);

Route::post('/invoice-pay-with-coingate',['as' => 'invoice.pay.with.coingate','uses' =>'CoingatePaymentController@invoicePayWithCoingate'])->middleware(['XSS']);
Route::get('/invoice/coingate/{invoice}', ['as' => 'invoice.coingate','uses' => 'CoingatePaymentController@getInvoicePaymentStatus']);

Route::post('/paymentwall' , ['as' => 'invoice.paymentwallpayment','uses' =>'PaymentWallPaymentController@invoicepaymentwall'])->middleware(['XSS']);
Route::post('/invoice-pay-with-paymentwall/{plan}',['as' => 'invoice.pay.with.paymentwall','uses' =>'PaymentWallPaymentController@invoicePayWithPaymentwall'])->middleware(['XSS']);
Route::get('/invoices/{flag}/{invoice}', ['as' => 'error.invoice.show','uses' => 'PaymentWallPaymentController@invoiceerror']);

//================================= End Invoice Payment Gateways  ====================================//


// Plan Request Module
Route::get('plan_request', 'PlanRequestController@index')->name('plan_request.index')->middleware(['auth','XSS',]);
Route::get('request_frequency/{id}', 'PlanRequestController@requestView')->name('request.view')->middleware(['auth','XSS',]);
Route::get('request_send/{id}', 'PlanRequestController@userRequest')->name('send.request')->middleware(['auth','XSS',]);
Route::get('request_response/{id}/{response}', 'PlanRequestController@acceptRequest')->name('response.request')->middleware(['auth','XSS',]);
Route::get('request_cancel/{id}', 'PlanRequestController@cancelRequest')->name('request.cancel')->middleware(['auth','XSS',]);
// End Plan Request Module



Route::get('invoices/pay/pdf/{id}', 'InvoiceController@pdffrominvoice')->name('invoice.download.pdf');

Route::post('/invoice-pay-with-stripe',['as' => 'invoice.pay.with.stripe','uses' =>'StripePaymentController@invoicePayWithStripe']);


//===========================================Import-Exort=================================================//

Route::get('export/project', 'ProjectController@export')->name('project.export');
Route::get('import/project/file', 'ProjectController@importFile')->name('project.file.import');
Route::post('import/project', 'ProjectController@import')->name('project.import');

Route::get('export/members', 'UserController@export')->name('members.export');
Route::get('import/members/file', 'UserController@importFile')->name('members.file.import');
Route::post('import/members', 'UserController@import')->name('members.import');


Route::get('import/invoice/file', 'InvoiceController@importFile')->name('invoice.file.import');
Route::post('import/invoice', 'InvoiceController@import')->name('invoice.import');

//===========================================screenshort=========================================//
Route::delete('tracker/{tid}/destroy', 'TimeTrackerController@Destroy')->name('tracker.destroy');
Route::get('time-tracker','TimeTrackerController@index')->name('time.tracker')->middleware(['auth','XSS']);
Route::get('projects/{id}/time-tracker','TimeTrackerController@projectTracks')->name('projects.time.tracker')->middleware(['auth','XSS']);
Route::post('tracker/image-view', ['as' => 'tracker.image.view','uses' => 'TimeTrackerController@getTrackerImages']);
Route::delete('tracker/image-remove', ['as' => 'tracker.image.remove','uses' => 'TimeTrackerController@removeTrackerImages']);

//===========================================ZoomMeeting=============================================//
Route::any('/setting/saveZoomSettings', ['as' => 'setting.ZoomSettings','uses' => 'SettingsController@saveZoomSettings'])->middleware(['auth','XSS']);

Route::get('zoommeeting/calendar', 'ZoomMeetingController@calendar')->name('zoommeeting.calendar')->middleware(['auth','XSS']);
// Route::get('/zoom/project/select/{id}', 'ZoomMeetingController@projectwiseuser')->name('zoom.project.select');
 Route::get('/zoom/projects/select/{id}', 'ZoomMeetingController@projectwiseclient')->name('zoom.projects.select');
Route::resource('zoommeeting', 'ZoomMeetingController')->middleware(['auth','XSS']);

//=======================================Slack Notification============================================//
Route::post('setting/slack','SettingsController@slack')->name('slack.setting');

//=======================================Telegram Notification============================================//
Route::post('setting/Telegram','SettingsController@telegram')->name('telegram.setting');

//==================================Recaptcha================================
Route::post('/recaptcha-settings',['as' => 'recaptcha.settings.store','uses' =>'SettingsController@recaptchaSettingStore'])->middleware(['auth','XSS']);

// ==================================================================================================================

// Contracttype Module
Route::resource('contract', 'ContractTypeController')->middleware(['auth','XSS']);
// End contract

//==================================== Contract ======================================//

Route::resource('contractclient', 'ContractController')->middleware(['auth','XSS']);

Route::POST('get-projects', 'ContractController@clientByProject')->name('project.by.user.id')->middleware(['auth','XSS']);
Route::post('contract/{id}/contract_description', 'ContractController@descriptionStore')->name('contract.contract_description.store')->middleware(['auth']);

// contract-attachments/file upload
Route::post('/contract/{id}/file', ['as' => 'contracts.file.upload','uses' => 'ContractController@fileUpload',])->middleware(['auth','XSS']);
Route::get('/contract/{id}/file/{fid}', ['as' => 'contracts.file.download','uses' => 'ContractController@fileDownload',])->middleware(['auth','XSS']);
Route::get('file/delete/{id}', ['as' => 'contracts.file.delete','uses' => 'ContractController@fileDelete',])->middleware(['auth','XSS']);

// contract-comment
Route::post('/contract/{id}/comment', ['as' => 'comment_store.store', 'uses' => 'ContractController@commentStore',])->middleware(['auth']);
Route::get('/contract/{id}/comment', ['as' => 'comment_store.destroy','uses' => 'ContractController@commentDestroy']);

// contract-notes
Route::post('/contract/{id}/notes', ['as' => 'note_store.store', 'uses' => 'ContractController@noteStore',])->middleware(['auth']);
Route::get('/contract/{id}/notes', ['as' => 'note_store.destroy','uses' => 'ContractController@noteDestroy',])->middleware(['auth']);

// contract-copy
Route::get('/contract-copy/{id}',['as' => 'contracts.copy','uses' =>'ContractController@copycontract'])->middleware(['auth','XSS']);
Route::post('/contract/copy/store/{id}',['as' => 'contracts.copy.store','uses' =>'ContractController@copycontractstore'])->middleware(['auth','XSS']);

// contract-download
Route::get('contract/pdf/{id}', 'ContractController@pdffromcontract')->name('contract.download.pdf');
Route::get('contract/{id}/get_contract', 'ContractController@printContract')->name('get.contract');

// signature
Route::get('/signature/{id}', 'ContractController@signature')->name('signature')->middleware(['auth','XSS']);
Route::post('/signaturestore', 'ContractController@signatureStore')->name('signaturestore')->middleware(['auth','XSS']);

// Email
Route::get('/contract/{id}/mail', ['as' => 'send.mail.contract','uses' => 'ContractController@sendmailContract',]);

Route::post('/contract_status_edit/{id}', 'ContractController@contract_status_edit')->name('contract.status')->middleware(['auth','XSS']);

////**===================================== Project Reports ==================================================////

Route::resource('/report_project','ProjectReportController')->middleware(['auth','XSS']);
Route::post('/report_project_data','ProjectReportController@ajax_data')->name('projects.ajax')->middleware(['auth','XSS']);
Route::post('/report_project/{id}','ProjectReportController@show')->name('project_report.show')->middleware(['auth','XSS']);

Route::post('/report_project/tasks/{id}',['as' => 'tasks.report.ajaxdata','uses' =>'ProjectReportController@ajax_tasks_report'])->middleware(['auth','XSS']);
Route::get('export/task_report/{id}', 'ProjectReportController@export')->name('project_report.export');

app/Models/Contract.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Contract extends Model
{
    protected $fillable = [
        'name',
        'client',
        'project',
        'subject',
        'value',
        'type',
        'start_date',
        'end_date',
        'notes',
        'description',
        'client_signature',
        'owner_signature',
        'created_by',
        'status',
    ];    

    public function ContractType()
    {
        return $this->hasOne('App\Models\ContractType', 'id', 'type');
    } 

    public function getprojectname()
    {
        return $this->hasOne('App\Models\Project', 'id', 'project');
    }

    public function clientdetail()
    {
        return $this->hasOne('App\Models\User', 'id', 'client');
    } 
   

    public function comment()
    {
        return $this->hasMany('App\Models\ContractComment', 'contract_id', 'id');
    }
    public function note()
    {
        return $this->hasMany('App\Models\ContractNote', 'contract_id', 'id');
    } 

    public function taskFiles()
    {
        return $this->hasMany('App\Models\ContractAttechment', 'contract_id' , 'id');
        // dd($this);
    }

    public static function getContractSummary($contracts)
    {
        $total = 0;

        foreach($contracts as $contract)
        {
            $total += $contract->value;
        }

        return \Auth::user()->priceFormat($total);
    }


      public static function editstatus()
    {

        $editstatus = [
            'accept' => 'Accept',
            'decline' => 'Decline',
           
        ];
        return $editstatus;
    }


}

app/Models/ContractType.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class ContractType extends Model
{
    protected $fillable = [
        'name',
        'created_by',
    ];
}

resources/views/contracts/contract_view.blade.php
@extends('layouts.invoicepayheader')
@section('content')
    <div class="row">

        <div class="col-lg-12">
            <div class="container">
                <div>
                    <div class="download-btn">
                        <a href="{{ route('contract.download.pdf', \Crypt::encrypt($contract->id)) }}"
                            class="btn btn-sm btn-white btn-icon-only rounded-circle ml-0 " data-toggle="tooltip"
                            data-original-title="{{ __('Download') }}">
                            <span class="btn-inner--icon"><i class="fas fa-download"></i></span>
                        </a>
                    </div>

                    <div class="card  " id="printTable" style="max-width: 1000px !important; min-width: 1000px !important;">

                        <div class="img-view p-4">
                            
                                <div class="col-8">
                                    <img src="{{ $img }}" class="contract_logos" style="filter: drop-shadow(2px 4px 6px black)">
                                </div>
                               
                                <div class="col-lg-12 col-md-4 mt-3">
                                    <h6 class="d-inline-block m-0 d-print-none">{{ __('Contract :') }}
                                    </h6>
                                    <span class="col-4"><h6
                                            class="text-md d-inline-block m-0 d-print-none">{{ App\Models\Utility::contractNumberFormat($contract->id) }}</span></span>
                                </div>  
                        </div>


                        <div class="card-body view p-4" style="height: auto !important;">
                            <div class="row align-items-center mb-4">

                                <div class="col-sm-12 mb-3 mb-sm-0">
                                    <div class="row  mt-3">
                                        <div class="col-8">
                                            <div class="col-lg-12 col-md-8">
                                                <h6 class="d-inline-block m-0 d-print-none">{{ __('Type   :') }}
                                                </h6>
                                                <span class="col-md-8"><span
                                                        class="text-md">{{ $contract->ContractType->name }}</span></span>
                                            </div>

                                            <div class="col-lg-12 col-md-8 mt-3">
                                                <h6 class="d-inline-block m-0 d-print-none">{{ __('Value  :') }}
                                                </h6>
                                                <span class="col-md-8"><span
                                                        class="text-md">{{ Auth::user()->priceFormat($contract->value) }}</span></span>
                                            </div>
                                        </div>


                                        <div class="col-4">
                                            <div class="col-12 text-right">
                                                <h6 class="d-inline-block m-0 d-print-none">{{ __('Start Date   :') }}</h6>
                                                <span class="col-md-8"><span
                                                        class="text-md">{{ Auth::user()->dateFormat($contract->start_date) }}</span></span>
                                            </div>
                                            <div class="col-12 text-right">
                                                <h6 class="d-inline-block m-0 d-print-none">{{ __('End Date   :') }}</h6>
                                                <span class="col-md-8"><span
                                                        class="text-md">{{ Auth::user()->dateFormat($contract->end_date) }}</span></span>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="col-12 mt-4">
                                      
                                        <div>{!! $contract->notes !!}</div>
                                        <br>
                                        <div>{!! $contract->contract_description !!}</div>
                                    </div>


                                    <div class="col-12 row d-flex mt-4">
                                        <div class="col-9">
                                            <img src="{!! $contract->owner_signature !!}" class="">
                                            <h5>{{ __('Owner Signature') }}</h5>
                                        </div>
                                        <div class="col-3 text-end">
                                            <img src="{!! $contract->client_signature !!}">
                                            <h5>{{ __('Client Signature') }}<h5>
                                        </div>

                                    </div>

                                </div>

                            </div>



                        </div>


                    </div>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/contracts/copy.blade.php
{{ Form::model($contract, ['route' => ['contracts.copy.store', $contract->id], 'method' => 'POST']) }}

    <div class="row">
        <div class="col-md-6 form-group">
            {{ Form::label('client_name', __('Client Name'), ['class' => 'col-form-label']) }}
            {{ Form::select('client_name', $client,$contract->client, ['class' => 'form-control select2', 'required' => 'required']) }}
        </div>

        {{-- {{ dd($contract->project->name) }} --}}
        <div class="col-md-6 form-group">
            {{ Form::label('project', __('Project'),['class'=>'col-form-label']) }}
            {{  Form::select('project', $project,null, array('class' => 'form-control select2','required'=>'required'))  }}
        </div>

        <div class="col-md-6 form-group">
            {{ Form::label('value', __('Value'),['class'=>'col-form-label']) }}
            {{ Form::number('value', null, array('class' => 'form-control','required'=>'required','min' => '1')) }}
        </div>

         <div class="col-md-6">
                    <div class="form-group">
                        {{ Form::label('subject', __('Subject'), ['class' => 'col-form-label']) }}
                        {{ Form::text('subject', null, ['class' => 'form-control ', 'required' => 'required']) }}
                    </div>
                </div>


        <div class="col-md-12 form-group">
            {{ Form::label('type', __('Type'), ['class' => 'col-form-label']) }}
            {{ Form::select('type', $contractType, null, ['class' => 'form-control select2', 'required' => 'required']) }}
        </div>

       <div class="form-group col-md-6">
                {{ Form::label('start_date', __('Start Date'),['class' => 'col-form-label']) }}
                {{ Form::date('start_date',  \Carbon\Carbon::now(), array('class' => 'form-control')) }}
            </div>
            <div class="form-group col-md-6">
                {{ Form::label('end_date', __('End Date'),['class' => 'col-form-label']) }}
                {{ Form::date('end_date',  \Carbon\Carbon::now(), array('class' => 'form-control')) }}
            </div>

            <div class="col-md-12 form-group">
                {{ Form::label('notes', __('Description'),['class'=>'col-form-label']) }}
                {{ Form::textarea('notes', null, array('class' => 'form-control')) }}
            </div>

    </div>


<div class="text-right pt-3">
    {{ Form::button(__('Duplicate'), ['type' => 'submit','class' => 'btn btn-sm btn-primary rounded-pill']) }}
    <button type="button" class="btn btn-sm btn-secondary rounded-pill" data-dismiss="modal">{{__('Cancel')}}</button>
</div>

{{ Form::close() }}

resources/views/contracts/index.blade.php
@extends('layouts.admin')

@section('title')
    {{ __('Manage Contract') }}
@endsection

@section('action-button')
   
@if (Auth::user()->type == 'owner')
    
    <a href="#" class="btn btn-sm btn-white btn-icon-only rounded-circle ml-2" data-url="{{ route('contractclient.create') }}" data-ajax-popup="true" data-size="lg" data-title="{{__('Create Contract')}}">
        <span class="btn-inner--icon"><i class="fas fa-plus"></i></span>
    </a>
    @endif

@endsection

@section('content')
    <div class="row">
        <div class="col-xl-3 col-6">
            <div class="card comp-card size">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="m-b-20">{{__('Total Contracts')}}</h6>
                            <h6 class="text-primary">{{ $cnt_contract['total'] }}</h6>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-handshake bg-success text-white"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div> 
        <div class="col-xl-3 col-6">
            <div class="card comp-card">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="m-b-20">{{__('This Month Total Contracts')}}</h6>
                            <h6 class="text-info">{{ $cnt_contract['this_month'] }}</h6>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-handshake bg-info text-white"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-6">
            <div class="card comp-card">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="m-b-20">{{__('This Week Total Contracts')}}</h6>
                            <h6 class="text-warning">{{ $cnt_contract['this_week'] }}</h6>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-handshake bg-warning text-white"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-6">
            <div class="card comp-card">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col">
                            <h6 class="m-b-20">{{__('Last 30 Days Total Contracts')}}</h6>
                            <h6 class="text-danger">{{ $cnt_contract['last_30days'] }}</h6>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-handshake bg-danger text-white"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="card-body table-border-style">
                    <div class="table-responsive">
                        <table class="table datatable" id="selection-datatable">
                            <thead>
                                <tr>
                                    <th>{{ __('Contract') }}</th>
                                    <th>{{ __('Project') }}</th>
                                    <th>{{ __('Subject') }}</th>
                                    <th>{{ __('Client Name') }}</th>
                                    <th>{{ __('Value') }}</th>
                                    <th>{{ __('Type') }}</th>
                                    <th>{{ __('Start Date') }}</th>
                                    <th>{{ __('End Date') }}</th>
                                    <th>{{ __('Status') }}</th>
                                    <th width="250px">{{ __('Action') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($contracts as $contract)
                                    <tr>    
                                        <td class="id">
                                            <a href="{{ route('contractclient.show', $contract->id) }}" class="btn btn-outline-primary">{{ App\Models\Utility::contractNumberFormat($contract->id) }}</a>
                                        </td>
                                        <td>{{!empty($contract->getprojectname) ? $contract->getprojectname->name : '-' }} </td>
                                         <td>{{$contract->subject}} </td>    
                                        <td>{{ !empty($contract->clientdetail) ? $contract->clientdetail->name : '-' }}</td>
                                        <td>{{ Auth::user()->priceFormat($contract->value) }}</td>
                                        <td>{{ !empty($contract->ContractType) ? $contract->ContractType->name : '-' }}</td>
                                        <td>{{ Auth::user()->dateFormat($contract->start_date) }}</td>
                                        <td>{{ Auth::user()->dateFormat($contract->end_date) }}</td>
                                        <td>  
                                                 @if($contract->status == 'pending')
                                                  <span class="badge badge-pill badge-warning">{{__('Pending')}}</span>
                                                 @elseif($contract->status == 'accept')
                                                  <span class="badge badge-pill badge-success">{{__('Accept')}}</span>
                                                  @else
                                                   <span class="badge badge-pill badge-danger">{{__('Decline')}}</span>
                                                 @endif
                                        </td>
                                        <td>
                                             <div class="actions">
                                               @if($contract->status == 'accept' && Auth::user()->type == 'owner')
                                                <a href="#" class="action-item px-2"  data-url="{{route('contracts.copy',$contract->id)}}"  data-ajax-popup="true" data-size="lg"  data-title="{{__('Duplicate')}}" data-toggle="tooltip" data-original-title="{{__('Duplicate')}}">
                                                    <i class="fas fa-copy"></i>
                                                </a>
                                                 @endif
                                                  
                                                <a href="{{ route('contractclient.show', $contract->id) }}" class="action-item px-2"   data-title="{{__('Show')}}" data-toggle="tooltip" data-original-title="{{__('Show')}}">
                                                    <i class="fas fa-eye"></i>
                                                </a>  
                                                @if (Auth::user()->type == 'owner')
                                                <a href="#" class="action-item px-2" data-url="{{ route('contractclient.edit',$contract->id) }}" data-ajax-popup="true" data-size="lg" data-title="{{__('Edit')}}" data-toggle="tooltip" data-original-title="{{__('Edit')}}">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                @endif
                                                @if (Auth::user()->type == 'owner')
                                                    <a href="#" class="action-item text-danger px-2" data-toggle="tooltip" data-original-title="{{__('Delete')}}" data-confirm="{{__('Are You Sure?')}}|{{__('This action can not be undone. Do you want to continue?')}}" data-confirm-yes="document.getElementById('delete-tax-{{$contract->id}}').submit();">
                                                        <i class="fas fa-trash-alt"></i>
                                                    </a>
                                            </div>
                                                {!! Form::open(['method' => 'DELETE', 'route' => ['contractclient.destroy',$contract->id],'id'=>'delete-tax-'.$contract->id]) !!}
                                                {!! Form::close() !!}
                                                 @endif
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
@push('script')
    <script type="text/javascript">
        $(document).on('change', '.client_id', function() {
            var client_id=$(this).val();
            var data = {
                'client_id': client_id,
                _token: $('meta[name="csrf-token"]').attr('content')
                
            }
            $.ajax({
                type: "POST",
                url: "{{ route('project.by.user.id')}}",
                data: data,
                success: function(response) {
                    $('.project').html('');
                    $.each(response, function(index, value) {
                        
                       var html= '<option value="'+index+'">'+value+'</option>';
                           
                            $('.project').append(html);
                        });
                }
            });
           
        });

    </script>   





@endpush