routes/web.php
Route::get('append-timesheet-task-html', 'TimesheetController@appendTimesheetTaskHTML')->name('append.timesheet.task.html')->middleware(['auth', 'XSS']);
Route::get('timesheet-table-view', 'TimesheetController@filterTimesheetTableView')->name('filter.timesheet.table.view')->middleware(['auth', 'XSS']);
Route::get('timesheet-view', 'TimesheetController@filterTimesheetView')->name('filter.timesheet.view')->middleware(['auth', 'XSS']);
Route::get('timesheet-list', 'TimesheetController@timesheetList')->name('timesheet.list')->middleware(['auth', 'XSS']);
Route::get('timesheet-list-get', 'TimesheetController@timesheetListGet')->name('timesheet.list.get')->middleware(['auth', 'XSS']);

Route::get('/project/{id}/timesheet',['as' => 'timesheet.index','uses' =>'TimesheetController@timesheetView'])->middleware(['auth','XSS']);
Route::get('/project/{id}/timesheet/create',['as' => 'timesheet.create','uses' =>'TimesheetController@timesheetCreate'])->middleware(['auth','XSS']);
Route::post('/project/timesheet',['as' => 'timesheet.store','uses' =>'TimesheetController@timesheetStore'])->middleware(['auth','XSS']);
Route::get('/project/timesheet/{project_id}/edit/{timesheet_id}',['as' => 'timesheet.edit','uses' =>'TimesheetController@timesheetEdit'])->middleware(['auth','XSS']);
Route::post('/project/timesheet/update/{timesheet_id}',['as' => 'timesheet.update','uses' =>'TimesheetController@timesheetUpdate'])->middleware(['auth','XSS']);
Route::delete('/project/timesheet/{timesheet_id}',['as' => 'timesheet.destroy','uses' =>'TimesheetController@timesheetDestroy'])->middleware(['auth','XSS']);

// User_Todo Module
Route::post('/todo/create',['as' => 'todo.store','uses' =>'UserController@todo_store'])->middleware(['auth','XSS']);
Route::post('/todo/{id}/update',['as' => 'todo.update','uses' =>'UserController@todo_update'])->middleware(['auth','XSS']);
Route::delete('/todo/{id}',['as' => 'todo.destroy','uses' =>'UserController@todo_destroy'])->middleware(['auth','XSS']);
Route::get('/change/mode',['as' => 'change.mode','uses' =>'UserController@changeMode']);


// Site Setting
Route::get('/settings',['as' => 'settings','uses' =>'SettingsController@index'])->middleware(['auth','XSS']);
Route::post('/settings',['as' => 'settings.store','uses' =>'SettingsController@store'])->middleware(['auth']);

// Send Test Email
Route::POST('/emailCheck',['as' => 'test.email','uses' =>'SettingsController@testEmail'])->middleware(['auth','XSS']);
Route::post('/emailCheck/send',['as' => 'test.email.send','uses' =>'SettingsController@testEmailSend'])->middleware(['auth','XSS']);

// Email Templates
Route::get('email_template_lang/{id}/{lang?}', 'EmailTemplateController@manageEmailLang')->name('manage.email.language')->middleware(['auth']);
Route::post('email_template_store/{pid}', 'EmailTemplateController@storeEmailLang')->name('store.email.language')->middleware(['auth']);
Route::post('email_template_status/{id}/{pid}', 'EmailTemplateController@updateStatus')->name('status.email.language')->middleware(['auth']);
Route::get('email_template','EmailTemplateController@index')->name('email_template.index')->middleware(['auth']);
Route::post('email_template','EmailTemplateController@store')->name('email_template.store')->middleware(['auth']);
Route::post('email_template/update/{id}','EmailTemplateController@update')->name('email_template.update')->middleware(['auth']);
// End Email Templates

// Plan Request Module
Route::get('plan_request', 'PlanRequestController@index')->name('plan_request.index')->middleware(['auth','XSS',]);
Route::get('request_frequency/{id}', 'PlanRequestController@requestView')->name('request.view')->middleware(['auth','XSS',]);
Route::get('request_send/{id}/{duration}', 'PlanRequestController@userRequest')->name('send.request')->middleware(['auth','XSS',]);
Route::get('request_response/{id}/{response}', 'PlanRequestController@acceptRequest')->name('response.request')->middleware(['auth','XSS',]);
Route::get('request_cancel/{id}', 'PlanRequestController@cancelRequest')->name('request.cancel')->middleware(['auth','XSS',]);
// End Plan Request Module

// Plan Route
Route::get('user/{id}/plan', 'UserController@upgradePlan')->name('plan.upgrade')->middleware(['auth','XSS',]);
Route::get('user/{id}/plan/{pid}', 'UserController@activePlan')->name('plan.active')->middleware(['auth','XSS',]);
Route::resource('plans', 'PlanController')->middleware(['auth','XSS']);
Route::get('/orders',['as'=>'order_list','uses'=>'PlanController@orderList'])->middleware(['auth','XSS']);
// end Plan route

// Stripe
Route::get('/payment/{code}', ['as'=>'payment','uses'=>'StripePaymentController@payment'])->middleware(['auth','XSS']);
// end stripe

// Coupon
Route::get('/apply-coupon', ['as' => 'apply.coupon','uses' =>'CouponController@applyCoupon'])->middleware(['auth','XSS']);
Route::resource('coupons', 'CouponController')->middleware(['auth','XSS']);
// end coupon

// Invoice Module
Route::get( '/invoices/pay/{id}', ['as' => 'pay.invoice','uses' => 'InvoiceController@pay',])->middleware(['XSS',]);
Route::resource('invoices', 'InvoiceController')->middleware(['auth','XSS']);
Route::post('/project/invoice',['as' => 'project.client.json','uses' =>'InvoiceController@jsonClient'])->middleware(['auth','XSS']);

// Invoice Item
Route::get('invoices/{id}/products', 'InvoiceController@productAdd')->name('invoices.products.add')->middleware(['auth','XSS']);
Route::post('invoices/{id}/products', 'InvoiceController@productStore')->name('invoices.products.store')->middleware(['auth','XSS']);
Route::delete('invoices/{id}/products/{pid}', 'InvoiceController@productDelete')->name('invoices.products.delete')->middleware(['auth','XSS']);

// Invoice Payment
Route::get('invoices-payments', 'InvoiceController@payments')->name('invoices.payments')->middleware(['auth','XSS']);
Route::get('invoices/{id}/payments', 'InvoiceController@paymentAdd')->name('invoices.payments.create')->middleware(['auth','XSS']);
Route::post('invoices/{id}/payments', 'InvoiceController@paymentStore')->name('invoices.payments.store')->middleware(['auth','XSS']);

//Client Invoice Payment
Route::post('/invoices/client/{id}/payment',['as' => 'client.invoice.payment','uses' =>'InvoiceController@addPayment'])->middleware(['auth', 'XSS']);
Route::post('/{id}/pay-with-paypal',['as' => 'client.pay.with.paypal','uses' =>'PaypalController@clientPayWithPaypal'])->middleware(['XSS']);
Route::get('/{id}/get-payment-status',['as' => 'client.get.payment.status','uses' =>'PaypalController@clientGetPaymentStatus'])->middleware(['XSS']);

// end invoice module

// Invoice Mail Send
Route::get('invoices/{id}/get_invoice', 'InvoiceController@printInvoice')->name('get.invoice')->middleware(['XSS']);
Route::get('invoice/{id}/payment/reminder', 'InvoiceController@paymentReminder')->name('invoice.payment.reminder');
Route::get('invoice/{id}/sent', 'InvoiceController@sent')->name('invoice.sent');

// Client Side Invoice Mail Send
Route::get('invoice/{id}/custom-send', 'InvoiceController@customMail')->name('invoice.custom.send')->middleware(['auth','XSS']);
Route::post('invoice/{id}/custom-mail', 'InvoiceController@customMailSend')->name('invoice.custom.mail')->middleware(['auth','XSS']);


// Invoice Template
Route::get('template/invoice',['as'=>'invoice.template.setting','uses'=>'InvoiceController@templateSetting'])->middleware(['auth','XSS']);
Route::post('/invoice-setting',['as' => 'invoice.template.store','uses' =>'InvoiceController@saveTemplateSettings'])->middleware(['auth','XSS']);
Route::get('/invoices/preview/{template}/{color}',['as' => 'invoice.preview','uses' =>'InvoiceController@previewInvoice']);

// Tax Module
Route::resource('taxes', 'TaxController')->middleware(['auth','XSS']);
// end tax

// ===================================================================================================================

Route::post('/plan-pay-with-paypal',['as' => 'plan.pay.with.paypal','uses' =>'PaypalController@planPayWithPaypal'])->middleware(['auth','XSS']);
Route::get('/{id}/plan-get-payment-status',['as' => 'plan.get.payment.status','uses' =>'PaypalController@planGetPaymentStatus'])->middleware(['auth','XSS']);

Route::get('/stripe-payment-status',['as' => 'stripe.payment.status','uses' =>'StripePaymentController@planGetStripePaymentStatus']);
Route::ANY('/stripe',['as'=>'stripe.post','uses'=>'StripePaymentController@stripePost']);
Route::post('/webhook-stripe',['as' => 'webhook.stripe','uses' =>'StripePaymentController@webhookStripe']);

Route::get('/take-a-plan-trial/{plan_id}', ['as' => 'take.a.plan.trial','uses' => 'PlanController@takeAPlanTrial'])->middleware(['auth','XSS']);
Route::get('/change-user-plan/{plan_id}', ['as' => 'change.user.plan','uses' => 'PlanController@changeUserPlan'])->middleware(['auth','XSS']);


//================================= Plan Payment Gateways Route ====================================//

Route::post('/plan-pay-with-paystack',['as' => 'plan.pay.with.paystack','uses' =>'PaystackPaymentController@planPayWithPaystack'])->middleware(['auth','XSS']);
Route::get('/plan/paystack/{pay_id}/{plan_id}', ['as' => 'plan.paystack','uses' => 'PaystackPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-flaterwave',['as' => 'plan.pay.with.flaterwave','uses' =>'FlutterwavePaymentController@planPayWithFlutterwave'])->middleware(['auth','XSS']);
Route::get('/plan/flaterwave/{txref}/{plan_id}', ['as' => 'plan.flaterwave','uses' => 'FlutterwavePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-razorpay',['as' => 'plan.pay.with.razorpay','uses' =>'RazorpayPaymentController@planPayWithRazorpay'])->middleware(['auth','XSS']);
Route::get('/plan/razorpay/{txref}/{plan_id}', ['as' => 'plan.razorpay','uses' => 'RazorpayPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-paytm',['as' => 'plan.pay.with.paytm','uses' =>'PaytmPaymentController@planPayWithPaytm'])->middleware(['auth','XSS']);

app/Models/Plan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    protected $fillable = [
        'name',
        'monthly_price',
        'annual_price',
        'status',
        'trial_days',
        'max_users',
        'max_projects',
        'description',
    ];

    public function arrDuration()
    {
        return [
            'Unlimited' => 'Unlimited',
            'Month' => 'Per Month',
            'Year' => 'Per Year',
        ];
    }
}

resources/views/plans/create.blade.php
<form class="pl-3 pr-3" method="post" action="{{ route('plans.store') }}">
    @csrf
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="form-group">
                <label class="form-control-label" for="name">{{ __('Name') }}</label>
                <input type="text" class="form-control" id="name" name="name" required/>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="form-group">
                <div class="custom-control custom-switch mt-5 ml-5">
                    <input type="checkbox" class="custom-control-input" name="status" id="status" value="1">
                    <label class="custom-control-label form-control-label" for="status">{{__('Status')}}</label>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="form-group">
                <label class="form-control-label" for="monthly_price">{{ __('Monthly Price') }}</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">{{(env('CURRENCY') ? env('CURRENCY') : '$')}}</span>
                    </div>
                    <input type="number" min="0" class="form-control" id="monthly_price" name="monthly_price" required/>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
            <div class="form-group">
                <label class="form-control-label" for="annual_price">{{ __('Annual Price') }}</label>
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text">{{(env('CURRENCY') ? env('CURRENCY') : '$')}}</span>
                    </div>
                    <input type="number" min="0" class="form-control" id="annual_price" name="annual_price" required/>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="form-group">
                <label class="form-control-label" for="trial_days">{{ __('Trial Days') }}</label>
                <input type="number" class="form-control" id="trial_days" name="trial_days" required/>
                <span><small>{{__('Note: "-1" for Unlimited')}}</small></span>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="form-group">
                <label class="form-control-label" for="max_users">{{ __('Maximum Users') }}</label>
                <input type="number" class="form-control" id="max_users" name="max_users" required/>
                <span><small>{{__('Note: "-1" for Unlimited')}}</small></span>
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
            <div class="form-group">
                <label class="form-control-label" for="max_projects">{{ __('Maximum Projects') }}</label>
                <input type="number" class="form-control" id="max_projects" name="max_projects" required/>
                <span><small>{{__('Note: "-1" for Unlimited')}}</small></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group">
                <label class="form-control-label" for="description">{{ __('Description') }}</label>
                <textarea class="form-control" data-toggle="autosize" rows="3" id="description" name="description"></textarea>
            </div>
        </div>
    </div>
    <div class="text-right">
        <button class="btn btn-sm btn-primary rounded-pill" type="submit">{{ __('Create Plan') }}</button>
    </div>
</form>

resources/views/plans/edit.blade.php
<form class="pl-3 pr-3" method="post" action="{{ route('plans.update',$plan->id) }}">
    @csrf
    @method('put')

    <div class="row">
        <div class="{{ ($plan->id == 1) ? 'col-12' : 'col-xs-12 col-sm-12 col-md-6 col-lg-6' }}">
            <div class="form-group">
                <label class="form-control-label" for="name">{{ __('Name') }}</label>
                <input type="text" class="form-control" id="name" name="name" value="{{$plan->name}}" required/>
            </div>
        </div>
        @if($plan->id != 1)
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <div class="form-group">
                    <div class="custom-control custom-switch mt-5 ml-5">
                        <input type="checkbox" class="custom-control-input" name="status" id="status" value="1" {{($plan->status == 1) ? 'checked' : ''}}>
                        <label class="custom-control-label form-control-label" for="status">{{__('Status')}}</label>
                    </div>
                </div>
            </div>
        @endif
    </div>
    @if($plan->id != 1)
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <div class="form-group">
                    <label class="form-control-label" for="monthly_price">{{ __('Monthly Price') }}</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">{{(env('CURRENCY') ? env('CURRENCY') : '$')}}</span>
                        </div>
                        <input type="number" min="0" class="form-control" id="monthly_price" name="monthly_price" value="{{$plan->monthly_price}}" required/>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
                <div class="form-group">
                    <label class="form-control-label" for="annual_price">{{ __('Annual Price') }}</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">{{(env('CURRENCY') ? env('CURRENCY') : '$')}}</span>
                        </div>
                        <input type="number" min="0" class="form-control" id="annual_price" name="annual_price" value="{{$plan->annual_price}}" required/>
                    </div>
                </div>
            </div>
        </div>
    @endif
    <div class="row">
        @if($plan->id != 1)
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
                <div class="form-group">
                    <label class="form-control-label" for="trial_days">{{ __('Trial Days') }}</label>
                    <input type="number" class="form-control" id="trial_days" name="trial_days" value="{{$plan->trial_days}}" required/>
                    <span><small>{{__('Note: "-1" for Unlimited')}}</small></span>
                </div>
            </div>
        @endif
        <div class="{{ ($plan->id == 1) ? 'col-6' : 'col-xs-12 col-sm-12 col-md-4 col-lg-4' }}">
            <div class="form-group">
                <label class="form-control-label" for="max_users">{{ __('Maximum Users') }}</label>
                <input type="number" class="form-control" id="max_users" name="max_users" value="{{$plan->max_users}}" required/>
                <span><small>{{__('Note: "-1" for Unlimited')}}</small></span>
            </div>
        </div>
        <div class="{{ ($plan->id == 1) ? 'col-6' : 'col-xs-12 col-sm-12 col-md-4 col-lg-4' }}">
            <div class="form-group">
                <label class="form-control-label" for="max_projects">{{ __('Maximum Projects') }}</label>
                <input type="number" class="form-control" id="max_projects" name="max_projects" value="{{$plan->max_projects}}" required/>
                <span><small>{{__('Note: "-1" for Unlimited')}}</small></span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="form-group">
                <label class="form-control-label" for="description">{{ __('Description') }}</label>
                <textarea class="form-control" data-toggle="autosize" rows="3" id="description" name="description">{{$plan->description}}</textarea>
            </div>
        </div>
    </div>
    <div class="text-right">
        <button class="btn btn-sm btn-primary rounded-pill" type="submit">{{ __('Update Plan') }}</button>
    </div>
</form>

resources/views/plans/index.blade.php
@extends('layouts.admin')

@section('title')
    {{__('Manage Plans')}}
@endsection

@section('action-button')
    <a href="#" class="btn btn-sm btn-white btn-icon-only rounded-circle ml-2" data-url="{{ route('plans.create') }}" data-ajax-popup="true" data-size="lg" data-title="{{__('Create Plans')}}">
        <span class="btn-inner--icon"><i class="fas fa-plus"></i></span>
    </a>
@endsection

@section('content')
    <div class="row">
        @foreach ($plans as $key => $plan)
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4 mt-4">
                <div class="card card-pricing popular text-center px-3 mb-5 mb-lg-0">
                    <span class="h6 w-60 mx-auto px-4 py-1 rounded-bottom bg-primary text-white">{{ $plan->name }}</span>
                    <a href="#" class="dropdown-item" data-ajax-popup="true" data-size="lg" data-title="{{__('Edit Plan')}}" data-url="{{route('plans.edit',$plan->id)}}"><i class="mdi mdi-pencil mr-1"></i>{{__('Edit')}}</a>
                    <div class="card-body delimiter-top">
                        <ul class="list-unstyled mb-4">
                            @if($plan->id != 1)
                                <li>{{ __('Trial') }} : {{$plan->trial_days}} {{ __('Days') }}</li>
                                <li>{{ __('Monthly Price') }} : {{(env('CURRENCY') ? env('CURRENCY') : '$')}}{{$plan->monthly_price}}</li>
                                <li>{{ __('Annual Price') }} : {{(env('CURRENCY') ? env('CURRENCY') : '$')}}{{$plan->annual_price}}</li>
                            @endif
                            <li>{{ ($plan->max_users < 0)?__('Unlimited'):$plan->max_users }} {{__('Users')}}</li>
                            <li>{{ ($plan->max_projects < 0)?__('Unlimited'):$plan->max_projects }} {{__('Projects')}}</li>
                            @if($plan->description)
                                <li>
                                    <small>{{$plan->description}}</small>
                                </li>
                            @endif

                            @if(\Auth::user()->type == 'owner' && \Auth::user()->plan == $plan->id)
                            <span class="clearfix"></span>
                            <div class="at_bottom">
                                <span class="badge badge-pill badge-success">{{__('Active')}}</span>
                            </div>
                        @endif



                        @if(($plan->id != \Auth::user()->plan) &&\Auth::user()->type != 'owner' )
                            @if($plan->price > 0)
                                <a class="badge badge-pill badge-primary" href="{{route('stripe',\Illuminate\Support\Facades\Crypt::encrypt($plan->id))}}" data-toggle="tooltip" data-original-title="{{__('Buy Plan')}}">
                                    <i class="fas fa-cart-plus"></i>
                                </a>
                            @endif
                        @endif

                        @if(\Auth::user()->type == 'owner' && \Auth::user()->plan != $plan->id)
                            @if($plan->id != 1)
                                @if(\Auth::user()->requested_plan != $plan->id)
                                <div class="at_bottom">
                                    <a href="{{ route('send.request',[\Illuminate\Support\Facades\Crypt::encrypt($plan->id)]) }}" class="badge badge-pill badge-success" data-title="{{__('Send Request')}}" data-toggle="tooltip">
                                        <span class="btn-inner--icon"><i class="fas fa-share"></i></span>
                                    </a>
                                </div>
                                @else
                                <div class="at_bottom">
                                    <a href="{{ route('request.cancel',\Auth::user()->id) }}" class="badge badge-pill badge-danger" data-title="{{__('Cancle Request')}}" data-toggle="tooltip">
                                        <span class="btn-inner--icon"><i class="fas fa-times"></i></span>
                                    </a>
                                </div>
                                @endif
                            @endif
                        @endif
                        </ul>
                    </div>
                </div>
            </div>
        @endforeach
    </div>
@endsection

@push('script')
    <script>
        $(document).ready(function () {
            $(document).on('click', '#prevent_plan', function () {
                show_toastr('Error', '{{__('Please Enter Stripe or PayPal Payment Details.')}}', 'error');
            });
        });
    </script>
@endpush

resources/views/plans/orderlist.blade.php
@extends('layouts.admin')

@section('title')
    {{__('Orders')}}
@endsection

@section('content')
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table" width="100%">
                            <thead class="thead-light">
                            <tr>
                                <th>{{__('Order Id')}}</th>
                                <th>{{__('Name')}}</th>
                                <th>{{__('Plan Name')}}</th>
                                <th>{{__('Price')}}</th>
                                <th>{{__('Status')}}</th>
                                <th>{{__('Type')}}</th>
                                <th>{{__('Date')}}</th>
                                <th>{{__('Coupon')}}</th>
                                <th class="text-right">{{__('Invoice')}}</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if($orders->count() > 0)
                                @foreach($orders as $order)
                                    <tr>
                                        <td>{{$order->order_id}}</td>
                                        <td>{{$order->user_name}}</td>
                                        <td>{{$order->plan_name}}</td>
                                        <td>{{(env('CURRENCY') ? env('CURRENCY') : '$')}} {{number_format($order->price)}}</td>
                                        <td>
                                            @if($order->payment_status == 'succeeded' || $order->payment_status == 'approved')
                                                <span class="badge badge-success">{{ucfirst($order->payment_status)}}</span>
                                            @else
                                                <span class="badge badge-danger">{{ucfirst($order->payment_status)}}</span>
                                            @endif
                                        </td>
                                        <td>{{$order->payment_type}}</td>
                                        <td>{{$order->created_at->format('d M Y')}}</td>
                                        <td>{{!empty($order->use_coupon)?$order->use_coupon->coupon_detail->name:'-'}}</td>
                                        <td class="text-right">
                                            @if($order->receipt =='free coupon')
                                                <p>{{__('Used 100 % discount coupon code.')}}</p>
                                            @elseif(!empty($order->receipt))
                                                <a href="{{$order->receipt}}" target="_blank" class="text-primary"><i class="fas fa-file-invoice"></i></a>
                                            @else
                                                {{'-'}}
                                            @endif
                                        </td>
                                    </tr>
                                @endforeach
                            @else
                                <tr>
                                    <th scope="col" colspan="8"><h6 class="text-center">{{__('No Orders Found.')}}</h6></th>
                                </tr>
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/plans/paymentwall.blade.php
@php
    $plan_id= \Illuminate\Support\Facades\Crypt::decrypt($data['plan_id']);
    $plan = App\Models\Plan::find($plan_id);
    $plan_name = $plan->name;
    if($data['paymentwall_payment_frequency']=="monthly")
    {
      $plandata=App\Models\Plan::where('id',$plan_id)->first();
      $planprice=$plandata->monthly_price;
    }
    else
    {
       $plandata=App\Models\Plan::where('id',$plan_id)->first();
       $planprice=$plandata->annual_price;
    }
 @endphp

 @php
$logo = \App\Models\Utility::get_file('logo/');
@endphp

<head>
  <meta name="csrf-token" content="{{ csrf_token() }}">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Plan PaymentWall &dash; {{(Utility::getValByName('header_text')) ? Utility::getValByName('header_text') : config('app.name') }}</title>
  <link rel="icon" href="{{$logo.'favicon.png'}}" type="image/png">
</head>



{{-- {{ dd( $admin_payment_setting) }} --}}
<script src="https://api.paymentwall.com/brick/build/brick-default.1.5.0.min.js"> </script>
<div id="payment-form-container"> </div>
<script>
var brick = new Brick({
  public_key: '{{ $admin_payment_setting['paymentwall_public_key'] }}', // please update it to Brick live key before launch your project
  amount: '{{ $planprice }}' ,
  currency: 'USD',
  container: 'payment-form-container',
  action: '{{route("plan.pay.with.paymentwall",[$data["plan_id"],$data["coupon"],"amount" => $data['paymentwall_payment_frequency']])}}',
  form: {
    merchant: 'Paymentwall',
    product: '{{ $plan_name }}',
    pay_button: 'Pay',
    show_zip: true, // show zip code 
    show_cardholder: true // show card holder name 
  }
});

brick.showPaymentForm(function(data) {
    if(data.flag == 1){
      window.location.href ='{{route("error.plan.show",1)}}';
    }else{
      window.location.href ='{{route("error.plan.show",2)}}';
    }
  }, function(errors) {
    if(errors.flag == 1){
      window.location.href ='{{route("error.plan.show",1)}}';
    }else{
      window.location.href ='{{route("error.plan.show",2)}}';
    }
         
  });

</script>

resources/views/plans/subscription.blade.php
@extends('layouts.admin')

@section('title')
    {{__('Choose Plan')}}
@endsection

@section('content')
    @include('plans.planlist',['size'=>'4','paymentSetting'=>\App\Models\Utility::getPaymentSetting()])
@endsection

@push('script')
    <script>
        $(document).ready(function () {
            var tohref = '';

            @if(\Auth::user()->is_register_trial == 1)
            var tohref = $('#trial_{{ Auth::user()->interested_plan_id }}').attr("href");
            @elseif(\Auth::user()->interested_plan_id != 0)
            var tohref = $('#interested_plan_{{ Auth::user()->interested_plan_id }}').attr("href");
            @endif

            if (tohref != '') {
                window.location = tohref;
            }
        });
    </script>
@endpush