routes/web.php
Route::delete('/project/timesheet/{timesheet_id}',['as' => 'timesheet.destroy','uses' =>'TimesheetController@timesheetDestroy'])->middleware(['auth','XSS']);

// User_Todo Module
Route::post('/todo/create',['as' => 'todo.store','uses' =>'UserController@todo_store'])->middleware(['auth','XSS']);
Route::post('/todo/{id}/update',['as' => 'todo.update','uses' =>'UserController@todo_update'])->middleware(['auth','XSS']);
Route::delete('/todo/{id}',['as' => 'todo.destroy','uses' =>'UserController@todo_destroy'])->middleware(['auth','XSS']);
Route::get('/change/mode',['as' => 'change.mode','uses' =>'UserController@changeMode']);


// Site Setting
Route::get('/settings',['as' => 'settings','uses' =>'SettingsController@index'])->middleware(['auth','XSS']);
Route::post('/settings',['as' => 'settings.store','uses' =>'SettingsController@store'])->middleware(['auth']);

// Send Test Email
Route::POST('/emailCheck',['as' => 'test.email','uses' =>'SettingsController@testEmail'])->middleware(['auth','XSS']);
Route::post('/emailCheck/send',['as' => 'test.email.send','uses' =>'SettingsController@testEmailSend'])->middleware(['auth','XSS']);

// Email Templates
Route::get('email_template_lang/{id}/{lang?}', 'EmailTemplateController@manageEmailLang')->name('manage.email.language')->middleware(['auth']);
Route::post('email_template_store/{pid}', 'EmailTemplateController@storeEmailLang')->name('store.email.language')->middleware(['auth']);
Route::post('email_template_status/{id}/{pid}', 'EmailTemplateController@updateStatus')->name('status.email.language')->middleware(['auth']);
Route::get('email_template','EmailTemplateController@index')->name('email_template.index')->middleware(['auth']);
Route::post('email_template','EmailTemplateController@store')->name('email_template.store')->middleware(['auth']);
Route::post('email_template/update/{id}','EmailTemplateController@update')->name('email_template.update')->middleware(['auth']);
// End Email Templates

// Plan Request Module
Route::get('plan_request', 'PlanRequestController@index')->name('plan_request.index')->middleware(['auth','XSS',]);
Route::get('request_frequency/{id}', 'PlanRequestController@requestView')->name('request.view')->middleware(['auth','XSS',]);
Route::get('request_send/{id}/{duration}', 'PlanRequestController@userRequest')->name('send.request')->middleware(['auth','XSS',]);
Route::get('request_response/{id}/{response}', 'PlanRequestController@acceptRequest')->name('response.request')->middleware(['auth','XSS',]);
Route::get('request_cancel/{id}', 'PlanRequestController@cancelRequest')->name('request.cancel')->middleware(['auth','XSS',]);
// End Plan Request Module

// Plan Route
Route::get('user/{id}/plan', 'UserController@upgradePlan')->name('plan.upgrade')->middleware(['auth','XSS',]);
Route::get('user/{id}/plan/{pid}', 'UserController@activePlan')->name('plan.active')->middleware(['auth','XSS',]);
Route::resource('plans', 'PlanController')->middleware(['auth','XSS']);
Route::get('/orders',['as'=>'order_list','uses'=>'PlanController@orderList'])->middleware(['auth','XSS']);
// end Plan route

// Stripe
Route::get('/payment/{code}', ['as'=>'payment','uses'=>'StripePaymentController@payment'])->middleware(['auth','XSS']);
// end stripe

// Coupon
Route::get('/apply-coupon', ['as' => 'apply.coupon','uses' =>'CouponController@applyCoupon'])->middleware(['auth','XSS']);
Route::resource('coupons', 'CouponController')->middleware(['auth','XSS']);
// end coupon

// Invoice Module
Route::get( '/invoices/pay/{id}', ['as' => 'pay.invoice','uses' => 'InvoiceController@pay',])->middleware(['XSS',]);
Route::resource('invoices', 'InvoiceController')->middleware(['auth','XSS']);
Route::post('/project/invoice',['as' => 'project.client.json','uses' =>'InvoiceController@jsonClient'])->middleware(['auth','XSS']);

// Invoice Item
Route::get('invoices/{id}/products', 'InvoiceController@productAdd')->name('invoices.products.add')->middleware(['auth','XSS']);
Route::post('invoices/{id}/products', 'InvoiceController@productStore')->name('invoices.products.store')->middleware(['auth','XSS']);
Route::delete('invoices/{id}/products/{pid}', 'InvoiceController@productDelete')->name('invoices.products.delete')->middleware(['auth','XSS']);

// Invoice Payment
Route::get('invoices-payments', 'InvoiceController@payments')->name('invoices.payments')->middleware(['auth','XSS']);
Route::get('invoices/{id}/payments', 'InvoiceController@paymentAdd')->name('invoices.payments.create')->middleware(['auth','XSS']);
Route::post('invoices/{id}/payments', 'InvoiceController@paymentStore')->name('invoices.payments.store')->middleware(['auth','XSS']);

//Client Invoice Payment
Route::post('/invoices/client/{id}/payment',['as' => 'client.invoice.payment','uses' =>'InvoiceController@addPayment'])->middleware(['auth', 'XSS']);
Route::post('/{id}/pay-with-paypal',['as' => 'client.pay.with.paypal','uses' =>'PaypalController@clientPayWithPaypal'])->middleware(['XSS']);
Route::get('/{id}/get-payment-status',['as' => 'client.get.payment.status','uses' =>'PaypalController@clientGetPaymentStatus'])->middleware(['XSS']);

// end invoice module

// Invoice Mail Send
Route::get('invoices/{id}/get_invoice', 'InvoiceController@printInvoice')->name('get.invoice')->middleware(['XSS']);
Route::get('invoice/{id}/payment/reminder', 'InvoiceController@paymentReminder')->name('invoice.payment.reminder');
Route::get('invoice/{id}/sent', 'InvoiceController@sent')->name('invoice.sent');

// Client Side Invoice Mail Send
Route::get('invoice/{id}/custom-send', 'InvoiceController@customMail')->name('invoice.custom.send')->middleware(['auth','XSS']);
Route::post('invoice/{id}/custom-mail', 'InvoiceController@customMailSend')->name('invoice.custom.mail')->middleware(['auth','XSS']);


// Invoice Template
Route::get('template/invoice',['as'=>'invoice.template.setting','uses'=>'InvoiceController@templateSetting'])->middleware(['auth','XSS']);
Route::post('/invoice-setting',['as' => 'invoice.template.store','uses' =>'InvoiceController@saveTemplateSettings'])->middleware(['auth','XSS']);
Route::get('/invoices/preview/{template}/{color}',['as' => 'invoice.preview','uses' =>'InvoiceController@previewInvoice']);

// Tax Module
Route::resource('taxes', 'TaxController')->middleware(['auth','XSS']);
// end tax

// ===================================================================================================================

Route::post('/plan-pay-with-paypal',['as' => 'plan.pay.with.paypal','uses' =>'PaypalController@planPayWithPaypal'])->middleware(['auth','XSS']);
Route::get('/{id}/plan-get-payment-status',['as' => 'plan.get.payment.status','uses' =>'PaypalController@planGetPaymentStatus'])->middleware(['auth','XSS']);

Route::get('/stripe-payment-status',['as' => 'stripe.payment.status','uses' =>'StripePaymentController@planGetStripePaymentStatus']);
Route::ANY('/stripe',['as'=>'stripe.post','uses'=>'StripePaymentController@stripePost']);
Route::post('/webhook-stripe',['as' => 'webhook.stripe','uses' =>'StripePaymentController@webhookStripe']);

Route::get('/take-a-plan-trial/{plan_id}', ['as' => 'take.a.plan.trial','uses' => 'PlanController@takeAPlanTrial'])->middleware(['auth','XSS']);
Route::get('/change-user-plan/{plan_id}', ['as' => 'change.user.plan','uses' => 'PlanController@changeUserPlan'])->middleware(['auth','XSS']);


//================================= Plan Payment Gateways Route ====================================//

Route::post('/plan-pay-with-paystack',['as' => 'plan.pay.with.paystack','uses' =>'PaystackPaymentController@planPayWithPaystack'])->middleware(['auth','XSS']);
Route::get('/plan/paystack/{pay_id}/{plan_id}', ['as' => 'plan.paystack','uses' => 'PaystackPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-flaterwave',['as' => 'plan.pay.with.flaterwave','uses' =>'FlutterwavePaymentController@planPayWithFlutterwave'])->middleware(['auth','XSS']);
Route::get('/plan/flaterwave/{txref}/{plan_id}', ['as' => 'plan.flaterwave','uses' => 'FlutterwavePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-razorpay',['as' => 'plan.pay.with.razorpay','uses' =>'RazorpayPaymentController@planPayWithRazorpay'])->middleware(['auth','XSS']);
Route::get('/plan/razorpay/{txref}/{plan_id}', ['as' => 'plan.razorpay','uses' => 'RazorpayPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-paytm',['as' => 'plan.pay.with.paytm','uses' =>'PaytmPaymentController@planPayWithPaytm'])->middleware(['auth','XSS']);
Route::post('/plan/paytm/{plan}', ['as' => 'plan.paytm','uses' => 'PaytmPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mercado',['as' => 'plan.pay.with.mercado','uses' =>'MercadoPaymentController@planPayWithMercado'])->middleware(['auth','XSS']);
Route::post('/plan/mercado', ['as' => 'plan.mercado','uses' => 'MercadoPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-mollie',['as' => 'plan.pay.with.mollie','uses' =>'MolliePaymentController@planPayWithMollie'])->middleware(['auth','XSS']);
Route::get('/plan/mollie/{plan}', ['as' => 'plan.mollie','uses' => 'MolliePaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-skrill',['as' => 'plan.pay.with.skrill','uses' =>'SkrillPaymentController@planPayWithSkrill'])->middleware(['auth','XSS']);
Route::get('/plan/skrill/{plan}', ['as' => 'plan.skrill','uses' => 'SkrillPaymentController@getPaymentStatus']);

Route::post('/plan-pay-with-coingate',['as' => 'plan.pay.with.coingate','uses' =>'CoingatePaymentController@planPayWithCoingate'])->middleware(['auth','XSS']);
Route::get('/plan/coingate/{plan}', ['as' => 'plan.coingate','uses' => 'CoingatePaymentController@getPaymentStatus']);

Route::post('/paymentwalls' , ['as' => 'plan.paymentwallpayment','uses' =>'PaymentWallPaymentController@paymentwall'])->middleware(['XSS']);
Route::post('/plan-pay-with-paymentwall/{plan}',['as' => 'plan.pay.with.paymentwall','uses' =>'PaymentWallPaymentController@planPayWithPaymentWall'])->middleware(['XSS']);

app/Models/Invoice.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Invoice extends Model
{
    protected $fillable = [
        'invoice_id',
        'project_id',
        'client_id',
        'due_date',
        'tax_id',
        'created_by',
        'status',
    ];

    public static $status = [
        '1' => 'Not Paid',
        '2' => 'Partialy Paid',
        '3' => 'Sent',
        '4' => 'Unpaid',
        '5' => 'Paid',
    ];

    public static $status_color = [
        '1' => 'info',
        '2' => 'warning',
        '3' => 'success',
        '4' => 'warning',
        '5' => 'success',
    ];

    // Get Invoice Projects
    public function project()
    {
        return $this->hasOne('App\Models\Project', 'id', 'project_id');
    }

    // Get Invoice Client
    public function client()
    {
        return $this->hasOne('App\Models\User', 'id', 'client_id');
    }

    // Get Invoice Users
    public function user()
    {
        return $this->hasOne('App\Models\User', 'id', 'created_by');
    }

    // Get Invoice Based Tax
    public function tax()
    {
        return $this->hasOne('App\Models\Tax', 'id', 'tax_id');
    }

    // Get Invoice Item
    public function items()
    {
        return $this->hasMany('App\Models\InvoiceProduct', 'invoice_id', 'id');
    }

    // Get Invoice Payments
    public function payments()
    {
        return $this->hasMany('App\Models\InvoicePayment', 'invoice_id', 'id');
    }

    // Get Invoice Subtotal
    public function getSubTotal()
    {
        $subTotal = 0;
        foreach($this->items as $product)
        {
            $subTotal += $product->price;
        }

        return $subTotal;
    }

    // Get Invoice Tax
    public function getTax()
    {
        $tax = ($this->getSubTotal() * (!empty($this->tax) ? $this->tax->rate : 0)) / 100.00;

        return $tax;
    }

    // Get Invoice Tax
    public function getTotal()
    {
        return $this->getSubTotal() + $this->getTax();
    }

    // Get Invoice Due Amount
    public function getDue()
    {
        $due = 0;
        foreach($this->payments as $payment)
        {
            $due += $payment->amount;
        }

        return $this->getTotal() - $due;
    }

    // Change Invoice Status
    public static function change_status($invoice_id, $status)
    {
        $invoice         = Invoice::find($invoice_id);
        $invoice->status = $status;
        $invoice->update();
    }

    public function getTotalDiscount()
    {
        $totalDiscount = 0;
        foreach($this->items as $product)
        {
            $totalDiscount += $product->discount;
        }

        return $totalDiscount;
    }
}

resources/views/invoices/create.blade.php
{{ Form::open(array('url' => 'invoices')) }}
<div class="row">
    <div class="col-12 col-md-6">
        <div class="form-group">
            {{ Form::label('project_id', __('Project'),['class' => 'form-control-label']) }}
            <select class="form-control" name="project_id" id="project_id" required>
                @foreach($projects as $project)
                    <option value="{{ $project->id }}">{{ $project->name }}</option>
                @endforeach
            </select>
            <small>{{__('You can make invoice on your own project.')}}</small>
        </div>
    </div>
    <div class="col-12 col-md-6">
        <div class="form-group">
            {{ Form::label('client_id', __('Client'),['class' => 'form-control-label']) }}
            <select class="form-control" name="client_id" id="client_id" required>
            </select>
            <a href="{{route('users')}}" class="d-none" id="no_client"><small>{{__('Click here to create Client')}}</small></a>
        </div>
    </div>
    <div class="col-12 col-md-6">
        <div class="form-group">
            {{ Form::label('due_date', __('Due Date'),['class' => 'form-control-label']) }}
            {{ Form::date('due_date',  \Carbon\Carbon::now(), ['class' => 'form-control','required'=>'required']) }}
        </div>
    </div>
    <div class="col-12 col-md-6">
        <div class="form-group">
            {{ Form::label('tax_id', __('Tax %'),['class' => 'form-control-label']) }}
            {{ Form::select('tax_id',\Auth::user()->taxes->pluck('name','id'), null, ['class' => 'form-control','required'=>'required']) }}
            @if(\Auth::user()->taxes->count() == 0)
                <a href="{{route('settings')}}" id="no_tax"><small>{{__('Click here to create Tax')}}</small></a>
            @endif
        </div>
    </div>
</div>

<div class="text-right">
    {{ Form::button(__('Create'), ['type' => 'submit','class' => 'btn btn-sm btn-primary rounded-pill']) }}
    <button type="button" class="btn btn-sm btn-secondary rounded-pill" data-dismiss="modal">{{__('Cancel')}}</button>
</div>
{{ Form::close() }}

<script>
    $(document).ready(function () {
        $("select[name=project_id]").trigger('change');
    });
    $(document).on("change", "select[name=project_id]", function () {
        fillClient($(this).val());
    });
</script>

resources/views/invoices/edit.blade.php
{{ Form::model($invoice, array('route' => array('invoices.update', $invoice->id), 'method' => 'PUT')) }}
<div class="row">
    <div class="col-12 col-md-6">
        <div class="form-group">
            {{ Form::label('project_id', __('Project'),['class' => 'form-control-label']) }}
            <select class="form-control" name="project_id" id="project_id" required>
                @foreach($projects as $project)
                    <option value="{{ $project->id }}" {{ ($invoice->project_id == $project->id) ? 'selected' : '' }}>{{ $project->name }}</option>
                @endforeach
            </select>
            <small>{{__('You can make invoice on your own project.')}}</small>
        </div>
    </div>
    <div class="col-12 col-md-6">
        <div class="form-group">
            {{ Form::label('client_id', __('Client'),['class' => 'form-control-label']) }}
            <select class="form-control" name="client_id" id="client_id" required>
            </select>
            <a href="{{route('users')}}" class="d-none" id="no_client"><small>{{__('Click here to create Client')}}</small></a>
        </div>
    </div>
    <div class="col-12 col-md-6">
        <div class="form-group">
            {{ Form::label('due_date', __('Due Date'),['class' => 'form-control-label']) }}
            {{ Form::date('due_date',  null, ['class' => 'form-control','required'=>'required']) }}
        </div>
    </div>
    <div class="col-12 col-md-6">
        <div class="form-group">
            {{ Form::label('tax_id', __('Tax %'),['class' => 'form-control-label']) }}
            {{ Form::select('tax_id',\Auth::user()->taxes->pluck('name','id'), null, ['class' => 'form-control','required'=>'required']) }}
            @if(\Auth::user()->taxes->count() == 0)
                <a href="{{route('settings')}}" id="no_tax"><small>{{__('Click here to create Tax')}}</small></a>
            @endif
        </div>
    </div>
</div>

<div class="text-right">
    {{ Form::button(__('Update'), ['type' => 'submit','class' => 'btn btn-sm btn-primary rounded-pill']) }}
    <button type="button" class="btn btn-sm btn-secondary rounded-pill" data-dismiss="modal">{{__('Cancel')}}</button>
</div>
{{ Form::close() }}

<script>
    var client_id = '{{$invoice->client_id}}';
    $(document).ready(function () {
        $("select[name=project_id]").trigger('change');
    });
    $(document).on("change", "select[name=project_id]", function () {
        fillClient($(this).val(), client_id);
    });
</script>

resources/views/invoices/import.blade.php
@php
$logo = \App\Models\Utility::get_file('uploads/sample/');
@endphp

<div class="card bg-none card-box">
    {{ Form::open(array('route' => array('invoice.import'),'method'=>'post', 'enctype' => "multipart/form-data")) }}
    <div class="row"  style="padding: 15px 15px;">
        <div class="col-md-12 mb-2">
        <div class="d-flex align-items-center justify-content-between">
            {{Form::label('file',__('Download sample customer CSV file'),['class'=>'form-control-label w-auto m-0'])}}
            <div>
                <a href="{{$logo.'sample-client.xlsx'}}" class="btn btn-sm btn-primary">
                    <i class="fa fa-download"></i> {{__('Download')}}
                </a>
            </div> 
        </div>
        </div>
        <div class="col-md-12">
            {{Form::label('file',__('Select CSV File'),['class'=>'form-control-label'])}}
            <div class="choose-file form-group">
                <label for="file" class="form-control-label">
                    <div>{{__('Choose file here')}}</div>
                    <input type="file" class="form-control" name="file" id="file" data-filename="upload_file" required>
                </label>
                <p class="upload_file"></p>
            </div>
        </div>
        <div class="col-md-12 mt-6 text-right">
            <input type="submit" value="{{__('Upload')}}" class="btn btn-sm btn-primary rounded-pill">
            <input type="button" value="{{__('Cancel')}}" class="btn btn-sm btn-primary rounded-pill" data-dismiss="modal">
        </div>
    </div>
    {{ Form::close() }}
</div>

resources/views/invoices/index.blade.php
@extends('layouts.admin')

@section('title')
    {{__('Invoices')}}
@endsection


@php
$logo_path = \App\Models\Utility::get_file('/');
@endphp

@section('action-button')
    <a href="#" class="btn btn-sm btn-white btn-icon-only rounded-circle ml-2" data-url="{{ route('invoices.create') }}" data-ajax-popup="true" data-size="md" data-title="{{__('Create Invoice')}}">
        <span class="btn-inner--icon"><i class="fas fa-plus"></i></span>
    </a>
    <a href="#" class="btn btn-sm btn-white btn-icon-only rounded-circle" data-url="{{ route('invoice.file.import') }}" data-ajax-popup="true" data-title="{{__('Import Members CSV file')}}" data-toggle="tooltip">
        <i class="fa fa-file-csv"></i>
    </a>
@endsection

@section('content')
    <ul class="nav nav-dark nav-tabs nav-overflow" role="tablist">
        <li class="nav-item">
            <a href="#send" id="send-tab" class="nav-link active" data-toggle="tab" role="tab" aria-selected="true">
                {{__('Send')}}
            </a>
        </li>
        <li class="nav-item">
            <a href="#receive" id="receive-tab" class="nav-link" data-toggle="tab" role="tab" aria-selected="true">
                {{__('Received')}}
            </a>
        </li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane fade show active" id="send" role="tabpanel" aria-labelledby="send-tab">
            <div class="row">
                <div class="col-12 pb-4">
                    <span class="text-white font-weight-700">{{__('Note :')}}</span>
                    <span class="text-white">{{__('You have sent this invoice to your client.')}}</span>
                </div>
                @if($send_invoice->count() > 0)
                    @foreach($send_invoice as $invoice)
                        <div class="col-lg-4">
                            <div class="card hover-shadow-lg">
                                <div class="card-header border-0">
                                    <div class="row align-items-center">
                                        <div class="col-10">
                                            <h6 class="mb-0"><a href="{{route('invoices.show',$invoice->id)}}">{{ $invoice->project->name }}</a></h6>
                                        </div>
                                        <div class="col-2 text-right">
                                            <div class="actions">
                                                <div class="dropdown">
                                                    <a href="#" class="action-item" data-toggle="dropdown"><i class="fas fa-ellipsis-v"></i></a>
                                                    <div class="dropdown-menu dropdown-menu-right">
                                                        <a href="{{route('invoices.show',$invoice->id)}}" class="dropdown-item">
                                                            {{__('Show')}}
                                                        </a>
                                                        <a href="#" class="dropdown-item" data-url="{{ route('invoices.edit',[$invoice->id]) }}" data-ajax-popup="true" data-size="md" data-title="{{__('Edit ').\App\Models\Utility::invoiceNumberFormat($invoice->invoice_id)}}">
                                                            {{__('Edit')}}
                                                        </a>
                                                        <a href="#" class="dropdown-item" data-toggle="tooltip" data-original-title="{{__('Delete')}}" data-confirm="Are You Sure?|This action can not be undone. Do you want to continue?" data-confirm-yes="document.getElementById('delete-form-{{$invoice->id}}').submit();">
                                                            {{__('Delete')}}
                                                        </a>
                                                        {!! Form::open(['method' => 'DELETE', 'route' => ['invoices.destroy', $invoice->id],'id'=>'delete-form-'.$invoice->id]) !!}
                                                        {!! Form::close() !!}
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body pt-0">
                                    <div class="p-3 border border-dashed">
                                        <span class="text-sm text-muted font-weight-600">{{\App\Models\Utility::invoiceNumberFormat($invoice->invoice_id)}}</span>
                                        <div class="row align-items-center mt-3">
                                            <div class="col-6">
                                                <h6 class="mb-0">{{ \App\Models\Utility::projectCurrencyFormat($invoice->project_id,($invoice->getSubTotal()+$invoice->getTax()),true) }}</h6>
                                                <span class="text-sm text-muted">{{__('Amount')}}</span>
                                            </div>
                                            <div class="col-6">
                                                <h6 class="mb-0">{{ \App\Models\Utility::getDateFormated($invoice->due_date) }}</h6>
                                                <span class="text-sm text-muted">{{__('Due Date')}}</span>
                                            </div>
                                        </div>
                                    </div>
                                    @if($invoice->client != null)
                                    <div class="media mt-4 align-items-center">

                                            @if($invoice->client->avatar)
                                                <img  src="{{$logo_path.$invoice->client->avatar}}" class="avatar rounded-circle avatar-sm"  title="{{ $invoice->client->name }}"  >

                                              @else
                                               <img {{ $invoice->client->img_avatar }}  class="avatar rounded-circle avatar-sm" title="{{ $invoice->client->name }}" >
                                              @endif






                                        <div class="media-body pl-3">
                                            <div class="text-sm my-0">{{$invoice->client->name}} <span class="text-primary font-weight-600">{{'@'.__('client')}}</span></div>
                                        </div>
                                    </div>
                                        @endif
                                </div>
                            </div>
                        </div>
                    @endforeach
                @else
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h6 class="text-center my-3">{{__('No Invoice Found.')}}</h6>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div>
        <div class="tab-pane fade show" id="receive" role="tabpanel" aria-labelledby="receive-tab">
            <div class="row">
                <div class="col-12 pb-4">
                    <span class="text-white font-weight-700">{{__('Note :')}}</span>
                    <span class="text-white">{{__('You have got this invoice from user.')}}</span>
                </div>
                @if($receive_invoice->count() > 0)
                    @foreach($receive_invoice as $invoice)
                        <div class="col-lg-4">
                            <div class="card hover-shadow-lg">
                                <div class="card-header border-0">
                                    <div class="row align-items-center">
                                        <div class="col-10">
                                            <h6 class="mb-0"><a href="{{route('invoices.show',$invoice->id)}}">{{ $invoice->project->name }}</a></h6>
                                        </div>
                                    </div>
                                </div>
                                <div class="card-body pt-0">
                                    <div class="p-3 border border-dashed">
                                        <span class="text-sm text-muted font-weight-600">{{\App\Models\Utility::invoiceNumberFormat($invoice->invoice_id)}}</span>
                                        <div class="row align-items-center mt-3">
                                            <div class="col-6">
                                                <h6 class="mb-0">{{ \App\Models\Utility::projectCurrencyFormat($invoice->project_id,($invoice->getSubTotal()+$invoice->getTax()),true) }}</h6>
                                                <span class="text-sm text-muted">{{__('Amount')}}</span>
                                            </div>
                                            <div class="col-6">
                                                <h6 class="mb-0">{{ \App\Models\Utility::getDateFormated($invoice->due_date) }}</h6>
                                                <span class="text-sm text-muted">{{__('Due Date')}}</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="media mt-4 align-items-center">


                                              @if($invoice->user->avatar)
                                                <img  src="{{$logo_path.$invoice->user->avatar}}" class="avatar rounded-circle avatar-sm"  title="{{ $invoice->user->name }}"  >

                                              @else
                                               <img {{ $invoice->user->img_avatar }}  class="avatar rounded-circle avatar-sm" title="{{ $invoice->user->name }}" >
                                              @endif
                                        <div class="media-body pl-3">
                                            <div class="text-sm my-0">{{$invoice->user->name}} <span class="text-primary font-weight-600">{{'@'.__('user')}}</span></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                @else
                    <div class="col-12">
                        <div class="card">
                            <div class="card-body">
                                <h6 class="text-center my-3">{{__('No Invoice Found.')}}</h6>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script>
        function fillClient(project_id, selected = 0) {
            $.ajax({
                url: '{{route('project.client.json')}}',
                data: {project_id: project_id},
                type: 'POST',
                success: function (data) {
                    $('#client_id').html('');

                    if (data != '') {
                        $('#no_client').addClass('d-none');
                        $.each(data, function (key, data) {
                            var selected = '';
                            if (key == selected) {
                                selected = 'selected';
                            }
                            $("#client_id").append('<option value="' + key + '" ' + selected + '>' + data + '</option>');
                        });
                    } else {
                        $('#no_client').removeClass('d-none');
                    }
                }
            })
        }
    </script>
@endpush